# 0. Package, Library, Mode

In [88]:
from pybaseball import statcast, cache
cache.enable()  # 캐시 사용 → 반복 호출 방지

import pandas as pd
import numpy as np

from IPython.display import display, HTML
from datetime import datetime, timedelta
import os, io, json
from pathlib import Path
from typing import Dict, Tuple, Optional

import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid", color_codes=True)
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')  # 시각화 시 경고 메시지 제거
import shap

from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report, brier_score_loss,
    roc_auc_score, roc_curve
)
from sklearn.calibration import calibration_curve, CalibratedClassifierCV
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from scipy.stats import uniform, randint, mode
from xgboost import XGBClassifier
from xgboost import plot_importance
from lightgbm import LGBMClassifier

In [89]:
# display option
pd.reset_option("all")

In [90]:
# EDITOR_MODE (vsc, colab) selection
EDITOR_MODE = 'vsc'

if EDITOR_MODE == 'colab':
    from google.colab import drive
    drive.mount('/content/drive')

    # Colab 환경에서는 쉘 명령어로 pip 설치 가능
    !pip install -q pybaseball
    !pip install -q pyarrow
    !pip install -q xgboost
    !pip install -q lightgbm
    
elif EDITOR_MODE == 'vsc':
    pass

print("EDITOR_MODE : "+EDITOR_MODE)

EDITOR_MODE : vsc

# 1. Data Loader

In [91]:
COLAB_DATA_PATH = '/content/drive/MyDrive/'
VSC_DATA_PATH = '../data/'  
DATA_FILE_PATH = 'statcast_data.parquet'
INDICATOR_PATH = '../indicator/'            # 확인을 위해 print 할 데이터
WEB_DATA_PATH = '../web_data/'              # web 에 올릴 데이터

if EDITOR_MODE == 'colab':
    file_path = COLAB_DATA_PATH + DATA_FILE_PATH
elif EDITOR_MODE == 'vsc':
    file_path = VSC_DATA_PATH + DATA_FILE_PATH
    
print("data path : "+file_path)

data path : ../data/statcast_data.parquet

In [92]:
# statcast data to parquet

'''
# API에서 데이터 받아서 parquet으로 저장

years = [2025]
all_data = []

for year in years:
    start_date = f"{year}-03-29" 
    end_date = f"{year}-07-31"

    print(f"Fetching data for {year}...")
    year_data = statcast(start_dt=start_date, end_dt=end_date)
    year_data["season"] = year
    all_data.append(year_data)

data = pd.concat(all_data, ignore_index=True)

data.to_parquet(file_path)

print("데이터 저장 완료")


'''

'\n# API에서 데이터 받아서 parquet으로 저장\n\nyears = [2025]\nall_data = []\n\nfor year in years:\n    start_date = f"{year}-03-29" \n    end_date = f"{year}-07-31"\n\n    print(f"Fetching data for {year}...")\n    year_data = statcast(start_dt=start_date, end_dt=end_date)\n    year_data["season"] = year\n    all_data.append(year_data)\n\ndata = pd.concat(all_data, ignore_index=True)\n\ndata.to_parquet(file_path)\n\nprint("데이터 저장 완료")\n\n\n'

In [93]:
print("data")
df = pd.read_parquet(file_path)
df

data

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches,season
0,SL,2024-03-29,85.4,-1.25,6.04,"Adam, Jason",595281,592094,None,swinging_strike,...,3.24,-0.06,0.06,33.3,<NA>,<NA>,<NA>,<NA>,<NA>,2024
1,FF,2024-03-29,96.1,-1.09,6.13,"Adam, Jason",672386,592094,None,called_strike,...,0.86,0.82,0.82,36.8,<NA>,<NA>,<NA>,<NA>,<NA>,2024
2,FF,2024-03-29,95.6,-1.35,5.96,"Adam, Jason",662139,592094,None,ball,...,0.89,0.71,-0.71,34.5,<NA>,<NA>,<NA>,<NA>,<NA>,2024
3,FF,2024-03-29,95.3,-1.13,6.13,"Adam, Jason",457759,592094,None,ball,...,1.08,0.94,0.94,37.4,<NA>,<NA>,<NA>,<NA>,<NA>,2024
4,SL,2024-03-29,87.1,-1.62,5.64,"Parsons, Wes",664040,641149,field_out,hit_into_play,...,2.68,-0.03,0.03,41.7,<NA>,<NA>,<NA>,<NA>,<NA>,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204878,CU,2025-08-08,84.4,-1.57,6.57,"Schlittler, Cam",660821,693645,None,ball,...,4.28,-0.68,0.68,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025
1204879,SL,2025-08-08,92.4,-2.05,6.5,"Schlittler, Cam",643289,693645,single,hit_into_play,...,2.41,-0.81,-0.81,<NA>,-2.868897,16.744696,27.284989,43.677858,18.212971,2025
1204880,SI,2025-08-08,97.6,3.04,5.58,"Hader, Josh",502671,623352,None,foul,...,0.9,0.6,-0.6,<NA>,-5.887354,19.587314,40.244996,37.920149,8.135253,2025
1204881,FF,2025-08-08,97.9,-1.74,6.42,"Schlittler, Cam",660821,693645,field_out,hit_into_play,...,1.11,0.39,-0.39,<NA>,12.528492,-6.229275,20.247488,28.210805,32.777547,2025
1204882,SI,2025-08-08,96.5,2.81,5.72,"Hader, Josh",502671,623352,field_out,hit_into_play,...,0.81,0.54,-0.54,<NA>,10.583691,14.17172,18.542157,48.892601,13.91868,2025

In [ ]:
# parquet update

'''
# 사용자 지정 구간
start_date = "2025-08-09"   # 새 데이터 시작일
end_date   = "2025-08-20"   # 새 데이터 종료일

# 파일 경로 (위에서 만든 file_path 재사용)
if not os.path.exists(file_path):
    raise FileNotFoundError(f"⚠️ {file_path} 파일이 없습니다. 먼저 기본 데이터를 생성하세요.")

# 기존 데이터 불러오기
df_old = pd.read_parquet(file_path)
print(f"기존 데이터: {df_old.shape} rows, {df_old['game_date'].min()} ~ {df_old['game_date'].max()}")

# 새 데이터 받아오기
print(f"새 데이터 요청 중... ({start_date} ~ {end_date})\n")
df_new = statcast(start_dt=start_date, end_dt=end_date)


if df_new.empty:
    print("⚠️ 새 데이터가 없습니다. 기간을 확인하세요.")
else:
    print(f"새 데이터 수집 완료: {df_new.shape} rows")

    # 시즌 컬럼 추가 (기존 형식 맞추기)
    df_new["season"] = pd.to_datetime(df_new["game_date"]).dt.year
    print(f"시즌 컬럼 추가: {df_new.shape} rows\n")

    # 기존 데이터와 합치기 + 중복 제거
    df_combined = pd.concat([df_old, df_new], ignore_index=True)

    # 날짜순 정렬
    df_combined.sort_values(by=["game_date", "game_pk", "pitch_number"], inplace=True)

    # 덮어쓰기 저장
    df_combined.to_parquet(file_path, index=False)
    print(f"✅ 데이터 업데이트 완료 → {file_path}")
    print(f"현재 데이터: {df_combined.shape} rows, {df_combined['game_date'].min()} ~ {df_combined['game_date'].max()}")

'''

기존 데이터: (1204883, 119) rows, 2024-03-29 00:00:00 ~ 2025-08-08 00:00:00
새 데이터 요청 중... (2025-08-09 ~ 2025-08-20)

This is a large query, it may take a moment to complete

100%|██████████| 12/12 [00:39<00:00,  3.31s/it]

새 데이터 수집 완료: (48933, 118) rows
시즌 컬럼 추가: (48933, 119) rows

✅ 데이터 업데이트 완료 → ../data/statcast_data.parquet
현재 데이터: (1253816, 119) rows, 2024-03-29 00:00:00 ~ 2025-08-20 00:00:00

In [96]:
print("data")
df = pd.read_parquet(file_path)
df = df.sort_values(by=["game_date", "game_pk", "pitch_number"], ascending=[True, True, True]).reset_index(drop=True)
df

data

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches,season
0,SL,2024-03-29,85.4,-1.25,6.04,"Adam, Jason",595281,592094,None,swinging_strike,...,3.24,-0.06,0.06,33.3,<NA>,<NA>,<NA>,<NA>,<NA>,2024
1,FF,2024-03-29,96.1,-1.09,6.13,"Adam, Jason",672386,592094,None,called_strike,...,0.86,0.82,0.82,36.8,<NA>,<NA>,<NA>,<NA>,<NA>,2024
2,FF,2024-03-29,95.6,-1.35,5.96,"Adam, Jason",662139,592094,None,ball,...,0.89,0.71,-0.71,34.5,<NA>,<NA>,<NA>,<NA>,<NA>,2024
3,FF,2024-03-29,95.3,-1.13,6.13,"Adam, Jason",457759,592094,None,ball,...,1.08,0.94,0.94,37.4,<NA>,<NA>,<NA>,<NA>,<NA>,2024
4,SL,2024-03-29,87.1,-1.62,5.64,"Parsons, Wes",664040,641149,field_out,hit_into_play,...,2.68,-0.03,0.03,41.7,<NA>,<NA>,<NA>,<NA>,<NA>,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253811,SI,2025-08-20,94.6,-2.56,5.43,"Hanifee, Brenan",621043,669724,None,foul,...,2.28,1.18,1.18,<NA>,-15.990116,19.325155,38.429698,26.000944,15.248968,2025
1253812,CU,2025-08-20,81.3,-2.76,5.11,"Morton, Charlie",621043,450203,walk,ball,...,4.11,-1.46,-1.46,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025
1253813,CH,2025-08-20,87.2,0.66,5.76,"Valdez, Framber",650402,664285,double_play,hit_into_play,...,3.05,0.85,-0.85,<NA>,8.671484,7.974596,35.104375,40.343443,34.358927,2025
1253814,SI,2025-08-20,94.4,0.7,5.94,"Valdez, Framber",682985,664285,walk,ball,...,2.1,1.05,1.05,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025
1253815,SI,2025-08-20,95.4,-2.59,5.39,"Hanifee, Brenan",621043,669724,single,hit_into_play,...,2.18,1.34,1.34,<NA>,-3.091954,13.141779,35.775015,31.712152,17.387501,2025

In [ ]:
# date_match_dict

# 날짜와 매치 정보 추출
df['game_date'] = pd.to_datetime(df['game_date'])
df['date_str'] = df['game_date'].dt.strftime('%y%m%d')

# 매치 ID: "AWAY@HOME" 형태로 생성
df['match_id'] = df['away_team'] + "@" + df['home_team']

# 날짜별 매치 집합 생성
date_match_dict = (
    df.groupby('date_str')['match_id']
    .agg(lambda x: sorted(set(x)))  # 정렬된 리스트로 저장
    .to_dict()
)



'''
# 저장 경로
match_json_path = "date_match_dict.json"

# JSON으로 저장
with open(match_json_path, "w") as f:
    json.dump(date_match_dict, f, indent=2)

print(f"✅ Saved match list by date to {match_json_path}")
'''

✅ Saved match list by date to date_match_dict.json

In [10]:
print(type(date_match_dict))
# date_match_dict

<class 'dict'>

In [ ]:
# pred_match_dict -> date_match_dict 에서 start, end 조절하고 내일 경기 손으로 집어 넣은 dict


# --- 설정 ---
match_json_path = "date_match_dict.json"  # 기존 전체 매치 JSON
pred_json_path = "pred_match_dict.json"   # 추출된 매치 JSON

start_date = "250522"  # YYMMDD 형식
end_date   = "250822"  # YYMMDD 형식

# --- 로드 ---
with open(match_json_path, "r") as f:
    date_match_dict = json.load(f)

# --- 필터링 ---
pred_match_dict = {
    date: matches
    for date, matches in date_match_dict.items()
    if start_date <= date <= end_date
}

'''
# --- 저장 ---
with open(pred_json_path, "w") as f:
    json.dump(pred_match_dict, f, indent=2, ensure_ascii=False)

print(f"✅ Saved {len(pred_match_dict)} days of matches to {pred_json_path}")
print("날짜 범위:", start_date, "~", end_date)

'''

✅ Saved 88 days of matches to pred_match_dict.json
날짜 범위: 250522 ~ 250822

In [12]:
display(df)
# date_str, match_id 추가됨

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches,season,date_str,match_id
0,SL,2024-03-29,85.4,-1.25,6.04,"Adam, Jason",595281,592094,None,swinging_strike,...,0.06,33.3,<NA>,<NA>,<NA>,<NA>,<NA>,2024,240329,TOR@TB
1,FF,2024-03-29,96.1,-1.09,6.13,"Adam, Jason",672386,592094,None,called_strike,...,0.82,36.8,<NA>,<NA>,<NA>,<NA>,<NA>,2024,240329,TOR@TB
2,FF,2024-03-29,95.6,-1.35,5.96,"Adam, Jason",662139,592094,None,ball,...,-0.71,34.5,<NA>,<NA>,<NA>,<NA>,<NA>,2024,240329,TOR@TB
3,FF,2024-03-29,95.3,-1.13,6.13,"Adam, Jason",457759,592094,None,ball,...,0.94,37.4,<NA>,<NA>,<NA>,<NA>,<NA>,2024,240329,TOR@TB
4,SL,2024-03-29,87.1,-1.62,5.64,"Parsons, Wes",664040,641149,field_out,hit_into_play,...,0.03,41.7,<NA>,<NA>,<NA>,<NA>,<NA>,2024,240329,TOR@TB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204878,CU,2025-08-08,84.4,-1.57,6.57,"Schlittler, Cam",660821,693645,None,ball,...,0.68,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,250808,HOU@NYY
1204879,SL,2025-08-08,92.4,-2.05,6.5,"Schlittler, Cam",643289,693645,single,hit_into_play,...,-0.81,<NA>,-2.868897,16.744696,27.284989,43.677858,18.212971,2025,250808,HOU@NYY
1204880,SI,2025-08-08,97.6,3.04,5.58,"Hader, Josh",502671,623352,None,foul,...,-0.6,<NA>,-5.887354,19.587314,40.244996,37.920149,8.135253,2025,250808,HOU@NYY
1204881,FF,2025-08-08,97.9,-1.74,6.42,"Schlittler, Cam",660821,693645,field_out,hit_into_play,...,-0.39,<NA>,12.528492,-6.229275,20.247488,28.210805,32.777547,2025,250808,HOU@NYY
1204882,SI,2025-08-08,96.5,2.81,5.72,"Hader, Josh",502671,623352,field_out,hit_into_play,...,-0.54,<NA>,10.583691,14.17172,18.542157,48.892601,13.91868,2025,250808,HOU@NYY

# 2. Preprocessing

## 2-1 drop, fill, X y split

In [99]:
df_prepro = df.copy()

In [14]:
# df features name print
def print_columns_in_blocks(df, block_size=5): 
    cols = df.columns.tolist()
    print(f"총 컬럼 수: {len(cols)}\n")

    for i in range(0, len(cols), block_size):
        print(", ".join(cols[i:i+block_size]))


# print_columns_in_blocks(df)

In [15]:
# df features missing rate csv
def save_missing_report_csv(df, filename, round_ndigits=2):
    # round_ndigits: 결측률 반올림 자리수 (기본 2)

    total_rows = len(df)
    missing_count = df.isnull().sum()
    missing_percent = (missing_count / total_rows) * 100
    dtypes = df.dtypes
    sample_values = df.apply(lambda col: col.dropna().iloc[0] if col.dropna().size > 0 else None)

    report = pd.DataFrame({
        'Feature': df.columns,
        'Missing Count': missing_count.values,
        'Missing %': missing_percent.round(round_ndigits).values,
        'Dtype': dtypes.values,
        'Sample Value': sample_values.values
    })

    report.to_csv(INDICATOR_PATH + filename, index=False)
    print(f"저장 완료: {filename} (Colab 왼쪽 '파일탭'에서 다운로드 가능)")
    
# save_missing_report_csv(df_prepro, filename="2-1 missing_report.csv")

In [100]:

# meta, drop 분리
meta_features = [
    'game_pk',
    'inning', 'inning_topbot',
    'pitch_number',  # 이 타석 내에서의 투구 번호
    
    'home_team', 'away_team',
    'game_date',
    'batter', 'pitcher',
    'post_home_score', 'post_away_score',  # 최종 점수 → label
    'home_score', 'away_score',
    'events',
    
    'date_str', 'match_id'
]


drop_features = [
    #
    'player_name',
    'description',
    
    # 사용되지 않는 deprecated
    'spin_dir', 'spin_rate_deprecated',
    'break_angle_deprecated', 'break_length_deprecated',
    'tfs_deprecated', 'tfs_zulu_deprecated',
    
    #
    'des',
    'umpire',
    'sv_id',
    'pitcher_days_until_next_game', 'batter_days_until_next_game',
    
    # 중복 또는 의미 중복
    'age_pit_legacy', 
    'age_bat_legacy', 
    'home_score_diff',

    # 타겟 정보 포함 가능성 (데이터 누수 우려)
    'post_bat_score', 'post_fld_score',
    'delta_home_win_exp', 'delta_run_exp', 'delta_pitcher_run_exp',
    'home_win_exp', 'bat_win_exp',
    'bat_score', 'fld_score',
    
    # 단일 시즌 훈련 시 불필요
    'game_year', 'season',
    
    # fielder
    'fielder_2', 'fielder_3', 'fielder_4', 'fielder_5', 'fielder_6', 'fielder_7', 'fielder_8', 'fielder_9',
    
    # drop by missing (missing over 50%)
    'hit_location', 'bb_type',
    'on_3b', 'on_2b', 'on_1b',
    'hc_x', 'hc_y',
    'hit_distance_sc',
    'launch_speed', 'launch_angle', 'launch_speed_angle',
    'estimated_ba_using_speedangle', 'estimated_woba_using_speedangle',
    'woba_value', 'woba_denom',
    'babip_value', 'iso_value',
    'bat_speed',
    'swing_length',
    'estimated_slg_using_speedangle',
    'hyper_speed',
    'attack_angle', 'attack_direction',
    'swing_path_tilt',
    'intercept_ball_minus_batter_pos_x_inches', 'intercept_ball_minus_batter_pos_y_inches',
    
    # 
    
]



print("meta_features len : " + str(len(meta_features)))
print("drop_features len : " + str(len(drop_features)))

meta_features len : 16
drop_features len : 61

In [101]:
def preprocess_X_meta_y(df_prepro, meta_features, drop_features):
    # 1. meta
    df_meta = df_prepro[meta_features].copy()
    
    # 2. X
    df_drop = df_prepro.drop(columns=meta_features + drop_features)

    # 3. y
    
    def assign_label(row):
        if row['post_home_score'] > row['post_away_score']:
            return 1   # 홈 승
        elif row['post_home_score'] < row['post_away_score']:
            return 0   # 원정 승
        else:
            return 1   # 무승부는 홈 승 처리
        
    y = df_meta.groupby('game_pk').agg({
        'date_str': 'first',
        'match_id': 'first',
        
        'home_team': 'first',
        'away_team': 'first',
        
        'post_home_score': 'max',
        'post_away_score': 'max',
    }).reset_index()
    
    y['label'] = y.apply(assign_label, axis=1)
    
    return df_drop, df_meta, y

# X, y(label) split
X, meta, y = preprocess_X_meta_y(df_prepro, meta_features, drop_features)

In [102]:
# meta에서 고유 game_pk 순서 리스트
game_pk_order = meta['game_pk'].drop_duplicates().tolist()

# df_y를 game_pk 순서에 맞춰 재정렬
y = y.set_index('game_pk').loc[game_pk_order].reset_index()

In [103]:
# X, meta, y    shape
dataset_shapes = {
    "df": (X, meta, y),
}

# 결과를 저장할 리스트
summary = []

# 각 데이터셋에 대해 shape 정보 수집
for name, (X, meta, y) in dataset_shapes.items():
    summary.append({
        "Set": name,
        "X Shape": X.shape,
        "Meta Shape": meta.shape,
        "y Shape": y.shape
    })

# DataFrame으로 정리해서 출력
shape_df = pd.DataFrame(summary)
display(shape_df)

  Set        X Shape     Meta Shape    y Shape
0  df  (1253816, 44)  (1253816, 16)  (4296, 8)

In [20]:
# df meta excel

'''
# 상위 10개 샘플을 뽑기
sample_count = 10
meta_samples = {}

for col in meta.columns:
    meta_samples[col] = list(meta[col].head(sample_count))

# DataFrame으로 변환
df_meta_samples = pd.DataFrame(meta_samples)

# ✅ 엑셀로 저장 (원하면)
output_path = INDICATOR_PATH+"2-1 meta_sample_10.xlsx"
df_meta_samples.to_excel(output_path, index=False)
'''

'\n# 상위 10개 샘플을 뽑기\nsample_count = 10\nmeta_samples = {}\n\nfor col in meta.columns:\n    meta_samples[col] = list(meta[col].head(sample_count))\n\n# DataFrame으로 변환\ndf_meta_samples = pd.DataFrame(meta_samples)\n\n# ✅ 엑셀로 저장 (원하면)\noutput_path = INDICATOR_PATH+"2-1 meta_sample_10.xlsx"\ndf_meta_samples.to_excel(output_path, index=False)\n'

In [21]:
# df y excel

'''
output_path = INDICATOR_PATH + "2-1 y_summary.xlsx"
y.to_excel(output_path, index=False)
'''

'\noutput_path = INDICATOR_PATH + "2-1 y_summary.xlsx"\ny.to_excel(output_path, index=False)\n'

In [104]:
def check_topbot_pairing(meta, name):
    counts = meta.groupby("game_pk")["inning_topbot"].nunique()
    result = {
        "Set": name,
        "Total Games": len(counts),
        "Both Top/Bottom": (counts == 2).sum(),
        "Only Top or Bottom": (counts < 2).sum()
    }
    return result


# 모든 세트 검사
topbot_summary = pd.DataFrame([
    check_topbot_pairing(meta, "df")
])


# 표 형태로 출력
display(topbot_summary)

  Set  Total Games  Both Top/Bottom  Only Top or Bottom
0  df         4296             4296                   0

In [23]:
# label 통계 계산
label_1_count = (y['label'] == 1).sum()
label_0_count = (y['label'] == 0).sum()
label_1_pct = (label_1_count / len(y)) * 100
label_0_pct = (label_0_count / len(y)) * 100

# 결과를 DataFrame으로 정리
stats_df = pd.DataFrame({
    'Metric': ['y_shape', 'label_1_count', 'label_0_count', 'label_1_pct', 'label_0_pct'],
    'Value': [f"{y.shape[0]} x {y.shape[1]}", label_1_count, label_0_count, f"{label_1_pct:.2f}%", f"{label_0_pct:.2f}%"]
})

# 표 형태로 출력
display(stats_df)

          Metric     Value
0        y_shape  4130 x 8
1  label_1_count      2198
2  label_0_count      1932
3    label_1_pct    53.22%
4    label_0_pct    46.78%

In [24]:
print_columns_in_blocks(X)

총 컬럼 수: 44

pitch_type, release_speed, release_pos_x, release_pos_z, zone
game_type, stand, p_throws, type, balls
strikes, pfx_x, pfx_z, plate_x, plate_z
outs_when_up, vx0, vy0, vz0, ax
ay, az, sz_top, sz_bot, effective_speed
release_spin_rate, release_extension, release_pos_y, at_bat_number, pitch_name
if_fielding_alignment, of_fielding_alignment, spin_axis, bat_score_diff, age_pit
age_bat, n_thruorder_pitcher, n_priorpa_thisgame_player_at_bat, pitcher_days_since_prev_game, batter_days_since_prev_game
api_break_z_with_gravity, api_break_x_arm, api_break_x_batter_in, arm_angle

In [105]:
# X fill

X_missing = X

# 1) 평균으로 채우는 컬럼
fill_mean_cols = [
    'release_speed', 'release_pos_x', 'release_pos_z', 'pfx_x', 'pfx_z',
    'plate_x', 'plate_z', 'vx0', 'vy0', 'vz0', 'ax', 'ay', 'az',
    'sz_top', 'sz_bot', 'effective_speed', 'release_spin_rate',
    'release_extension', 'release_pos_y', 'spin_axis', 'api_break_z_with_gravity',
    'api_break_x_arm', 'api_break_x_batter_in', 'arm_angle'
]

for col in fill_mean_cols:
    mean_val = X_missing[col].mean()
    # Int64 타입은 정수로 변환 후 fill
    if pd.api.types.is_integer_dtype(X_missing[col].dtype):
        mean_val = int(round(mean_val))

    X_missing[col].fillna(mean_val, inplace=True)


# 2) 최빈값으로 채우는 컬럼
fill_mode_cols = ['zone']
for col in fill_mode_cols:
    mode_val = X_missing[col].mode().iloc[0]

    X_missing[col].fillna(mode_val, inplace=True)


# 3) 'Unknown' 또는 최빈값으로 채우는 object 타입 컬럼
fill_unknown_cols = ['pitch_type', 'pitch_name']
for col in fill_unknown_cols:
    X_missing[col].fillna('Unknown', inplace=True)


# 4) 고정값으로 채우는 컬럼
fill_constant = {
    'if_fielding_alignment': 'Standard',
    'of_fielding_alignment': 'Standard',
    'pitcher_days_since_prev_game': 0,
    'batter_days_since_prev_game': 0
}

for col, val in fill_constant.items():
    X_missing[col].fillna(val, inplace=True)


# 고정값 컬럼 리스트 정의 (keys만 사용)
fill_constant_cols = list(fill_constant.keys())

# 총 컬럼 개수 계산
total_fill_cols = len(fill_mean_cols + fill_mode_cols + fill_unknown_cols + fill_constant_cols)
print("filled len :", total_fill_cols)

filled len : 31

In [106]:
# X_missing -> fill check (결측치 전부 0인지 확인)
datasets = {
    "X_missing": X_missing,
}

# 결측치가 모두 0개인지 확인
for name, df in datasets.items():
    missing_per_col = df.isnull().sum()
    if (missing_per_col == 0).all():
        print(f"{name} every feature missing 0%")
    else:
        print(f"{name} has missing values:")
        print(missing_per_col[missing_per_col > 0])

X_missing every feature missing 0%

In [27]:
# X_missing 10 sample 

sample_data = []

# 각 컬럼별 상위 10개 샘플 추출
for col in X_missing.columns:
    top_samples = X_missing[col].head(10).tolist()  # 상위 10개 값
    sample_data.append([col] + top_samples)

# DataFrame으로 변환
# 첫 번째 컬럼은 'column_name', 이후는 sample_1, sample_2, ...
sample_df = pd.DataFrame(sample_data, columns=['column_name'] + [f'sample_{i+1}' for i in range(10)])

# Excel로 저장
output_file = INDICATOR_PATH + "2-1 X_missing_top10_samples.xlsx"
# sample_df.to_excel(output_file, index=False)

## 2-2 Encoding

In [107]:
# 복사본 생성 (원본 보존)
X_encoded = X_missing.copy()

In [108]:
# 1. Label Encoding (공통)

# 인코딩할 컬럼 목록
label_encode_cols = ['pitch_type', 'type', 'zone', 'pitch_name']


# 1. 인코딩 전 데이터 복사 (Before 저장용)
X_encoded = X_missing.copy()  # X_missing에서 fill된 데이터 사용
before_samples = X_encoded[label_encode_cols].copy()

# 2. 문자열 변환 (카테고리가 숫자로 바뀌는 문제 방지)
for col in label_encode_cols:
    X_encoded[col] = X_encoded[col].astype(str)

# 3. OrdinalEncoder로 인코딩
# OrdinalEncoder 인스턴스 생성 (unknown → -1로 처리)
# fit + transform (전체 X_encoded 기준)
ordinal_enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X_encoded[label_encode_cols] = ordinal_enc.fit_transform(X_encoded[label_encode_cols])


# Label Encoding excel
'''
# 4. Sheet1: Before-After 비교 (상위 10개)
sample_count = 10
compare_df = pd.DataFrame()

for col in label_encode_cols:
    compare_df[f"{col} (before)"] = before_samples[col].head(sample_count).values
    compare_df[f"{col} (after)"] = X_encoded[col].head(sample_count).astype(int).values


# 5. Sheet2~Sheet5: 각 컬럼별 매핑 테이블
mapping_dfs = {}
for i, col in enumerate(label_encode_cols):
    mapping_dfs[col] = pd.DataFrame({
        "category": ordinal_enc.categories_[i],
        "encoded_value": range(len(ordinal_enc.categories_[i]))
    })

# 6. Excel로 저장
with pd.ExcelWriter(INDICATOR_PATH+"2-2 label_encoding_summary.xlsx") as writer:
    compare_df.to_excel(writer, sheet_name="Before_After_Sample", index=False)
    for col in label_encode_cols:
        mapping_dfs[col].to_excel(writer, sheet_name=f"Mapping_{col}", index=False)
'''

'\n# 4. Sheet1: Before-After 비교 (상위 10개)\nsample_count = 10\ncompare_df = pd.DataFrame()\n\nfor col in label_encode_cols:\n    compare_df[f"{col} (before)"] = before_samples[col].head(sample_count).values\n    compare_df[f"{col} (after)"] = X_encoded[col].head(sample_count).astype(int).values\n\n\n# 5. Sheet2~Sheet5: 각 컬럼별 매핑 테이블\nmapping_dfs = {}\nfor i, col in enumerate(label_encode_cols):\n    mapping_dfs[col] = pd.DataFrame({\n        "category": ordinal_enc.categories_[i],\n        "encoded_value": range(len(ordinal_enc.categories_[i]))\n    })\n\n# 6. Excel로 저장\nwith pd.ExcelWriter(INDICATOR_PATH+"2-2 label_encoding_summary.xlsx") as writer:\n    compare_df.to_excel(writer, sheet_name="Before_After_Sample", index=False)\n    for col in label_encode_cols:\n        mapping_dfs[col].to_excel(writer, sheet_name=f"Mapping_{col}", index=False)\n'

In [30]:
'''
fit()
학습 데이터를 기준으로 라벨 인코딩의 매핑 규칙을 만든다
예: ['FF', 'SL', 'CU'] → [0, 1, 2]

transform()
이미 만든 매핑 규칙을 이용해서 실제 값을 변환한다
예: 'SL' → 1
'''

"\nfit()\n학습 데이터를 기준으로 라벨 인코딩의 매핑 규칙을 만든다\n예: ['FF', 'SL', 'CU'] → [0, 1, 2]\n\ntransform()\n이미 만든 매핑 규칙을 이용해서 실제 값을 변환한다\n예: 'SL' → 1\n"

In [31]:
print(X_encoded.shape)

(1204883, 44)

In [109]:
# 2. One-Hot Encoding
one_hot_cols = ['game_type', 'stand', 'p_throws', 'if_fielding_alignment', 'of_fielding_alignment']

# 1) 전체 가능한 dummy 컬럼 추출 (기준: X_encoded 전체 데이터)
dummy_all_columns = pd.get_dummies(X_encoded[one_hot_cols], columns=one_hot_cols).columns.tolist()

# 2) X_encoded에 대해 One-Hot Encoding 수행
df_dummies = pd.get_dummies(X_encoded[one_hot_cols], columns=one_hot_cols)

# 3) 누락된 컬럼 보정 (0으로 채우기)
for col in dummy_all_columns:
    if col not in df_dummies.columns:
        df_dummies[col] = 0

# 4) 컬럼 순서 맞춤
df_dummies = df_dummies[dummy_all_columns]

# 5) 기존 원본에서 one_hot_cols 삭제하고, 인코딩 결과 합치기
X_encoded = pd.concat([X_encoded.drop(columns=one_hot_cols), df_dummies], axis=1)


print(X_encoded.shape)

# 드롭 대상 컬럼 (희귀 + 불균형)
rare_alignment_cols = [
    'if_fielding_alignment_Infield shade',
    # 의미 : 미세한 내야 위치 조정
    # 빈도 : 희귀	
    # 중요도 : 낮음
    'of_fielding_alignment_4th outfielder'
    # 4명 외야수 배치 (전략적)	
    # 매우 희귀	
    # 매우 낮음 
]

X_encoded.drop(columns=rare_alignment_cols, errors='ignore', inplace=True)
print(f"✅ One-Hot Encoding 완료 (희귀 컬럼 제거 후): {X_encoded.shape}")


# One-Hot Encoding excel
'''
# One-Hot Encoding 확인
# (1) Sheet1: One-Hot Encoding 전 10개 샘플
sheet1 = X_missing[one_hot_cols].head(10).copy()

# (2) Sheet2: One-Hot Encoding 후 10개 샘플
sheet2 = df_dummies.drop(columns=rare_alignment_cols, errors='ignore').head(10).copy()

# Excel로 저장
with pd.ExcelWriter(INDICATOR_PATH+"2-2 onehot_encoding_summary.xlsx") as writer:
    sheet1.to_excel(writer, sheet_name="Before_OneHot", index=False)
    sheet2.to_excel(writer, sheet_name="After_OneHot", index=False)

print("✅ One-Hot Encoding 비교 결과 저장 완료 → onehot_encoding_summary.xlsx")
'''

(1253816, 50)
✅ One-Hot Encoding 완료 (희귀 컬럼 제거 후): (1253816, 48)

'\n# One-Hot Encoding 확인\n# (1) Sheet1: One-Hot Encoding 전 10개 샘플\nsheet1 = X_missing[one_hot_cols].head(10).copy()\n\n# (2) Sheet2: One-Hot Encoding 후 10개 샘플\nsheet2 = df_dummies.drop(columns=rare_alignment_cols, errors=\'ignore\').head(10).copy()\n\n# Excel로 저장\nwith pd.ExcelWriter(INDICATOR_PATH+"2-2 onehot_encoding_summary.xlsx") as writer:\n    sheet1.to_excel(writer, sheet_name="Before_OneHot", index=False)\n    sheet2.to_excel(writer, sheet_name="After_OneHot", index=False)\n\nprint("✅ One-Hot Encoding 비교 결과 저장 완료 → onehot_encoding_summary.xlsx")\n'

In [33]:
'''
pd.get_dummies()는 주어진 데이터에서 존재하는 값들만 기준으로 One-Hot Encoding을 수행

**stand**는 원래 컬럼 이름이고,
**stand_L, stand_R**  는 접두사(prefix)로 사용되어 만들어진 결과 컬럼
'''

'''
encoded_cols = [col for col in X_train_encoded.columns if col.startswith(prefix + '_')]
[<반환할 항목> for <항목> in <반복 대상> if <조건>]


if col.startswith(prefix + '_')
이 부분은 각 컬럼 이름이 특정 접두사로 시작하는지 확인합니다.

'stand_L'.startswith('stand_')  # True
'stand_R'.startswith('stand_')  # True
'pitch_type'.startswith('stand_')  # False
'''

"\nencoded_cols = [col for col in X_train_encoded.columns if col.startswith(prefix + '_')]\n[<반환할 항목> for <항목> in <반복 대상> if <조건>]\n\n\nif col.startswith(prefix + '_')\n이 부분은 각 컬럼 이름이 특정 접두사로 시작하는지 확인합니다.\n\n'stand_L'.startswith('stand_')  # True\n'stand_R'.startswith('stand_')  # True\n'pitch_type'.startswith('stand_')  # False\n"

In [34]:
print_columns_in_blocks(X_encoded)

총 컬럼 수: 48

pitch_type, release_speed, release_pos_x, release_pos_z, zone
type, balls, strikes, pfx_x, pfx_z
plate_x, plate_z, outs_when_up, vx0, vy0
vz0, ax, ay, az, sz_top
sz_bot, effective_speed, release_spin_rate, release_extension, release_pos_y
at_bat_number, pitch_name, spin_axis, bat_score_diff, age_pit
age_bat, n_thruorder_pitcher, n_priorpa_thisgame_player_at_bat, pitcher_days_since_prev_game, batter_days_since_prev_game
api_break_z_with_gravity, api_break_x_arm, api_break_x_batter_in, arm_angle, game_type_R
stand_L, stand_R, p_throws_L, p_throws_R, if_fielding_alignment_Standard
if_fielding_alignment_Strategic, of_fielding_alignment_Standard, of_fielding_alignment_Strategic

## 2-3 Outlier

In [35]:
#

## 2-4 Feature Engineering

In [110]:
X_FE = X_encoded.copy()

# time_aware_feature (빈 df로 초기화)
X_taf = pd.DataFrame(index=X_encoded.index)

In [111]:
def create_time_aware_feature(X): # 주어진 encoded dataframe에서 파생 피처 및 time-aware 를 생성하여 df_taf에 덮어씌움
    
    # 2) time operation
    def generate_time_features(base_series, prefix):
        return {
            f"{prefix}_rolling_avg_5": base_series.rolling(window=5, min_periods=1).mean(),
            f"{prefix}_lag_1": base_series.shift(1),
            f"{prefix}_diff_1": base_series.diff(),
        }
    # derived feature + time operation -> time aware feature

    all_features = []

    # 1) derived feature
    spin_eff = X["release_spin_rate"] / X["release_speed"]
    all_features.append(pd.DataFrame(generate_time_features(spin_eff, "spin_efficiency"), index=X.index))

    speed_gap = X["release_speed"] - X["effective_speed"]
    all_features.append(pd.DataFrame(generate_time_features(speed_gap, "speed_gap"), index=X.index))

    release_pos_angle = np.arctan(X["release_pos_z"] / (X["release_pos_x"] + 1e-6))
    all_features.append(pd.DataFrame(generate_time_features(release_pos_angle, "release_pos_angle"), index=X.index))

    plate_distance = np.sqrt(X["plate_x"]**2 + X["plate_z"]**2)
    all_features.append(pd.DataFrame(generate_time_features(plate_distance, "plate_distance"), index=X.index))

    init_velocity_vector = np.sqrt(X["vx0"]**2 + X["vy0"]**2 + X["vz0"]**2)
    all_features.append(pd.DataFrame(generate_time_features(init_velocity_vector, "init_velocity_vector"), index=X.index))

    pitch_movement_vector = np.sqrt(X["pfx_x"]**2 + X["pfx_z"]**2)
    all_features.append(pd.DataFrame(generate_time_features(pitch_movement_vector, "pitch_movement_vector"), index=X.index))

    speed_per_extension = X["release_speed"] / (X["release_extension"] + 1e-6)
    all_features.append(pd.DataFrame(generate_time_features(speed_per_extension, "speed_per_extension"), index=X.index))

    release_mechanics_profile = X["release_pos_y"] + X["release_extension"]
    all_features.append(pd.DataFrame(generate_time_features(release_mechanics_profile, "release_mechanics_profile"), index=X.index))

    vertical_spin_effect = X["spin_axis"] * X["pfx_z"]
    all_features.append(pd.DataFrame(generate_time_features(vertical_spin_effect, "vertical_spin_effect"), index=X.index))

    # 10.
    horizontal_spin_effect = X["release_spin_rate"] / (X["pfx_x"] + 1e-6)
    all_features.append(pd.DataFrame(generate_time_features(horizontal_spin_effect, "horizontal_spin_effect"), index=X.index))

    df_taf = pd.concat(all_features, axis=1)
    return df_taf

X_taf = create_time_aware_feature(X_encoded)

In [38]:
'''
1. Rolling Average: rolling(window=5, min_periods=1).mean()

과거 5개의 값을 평균해서 현재 시점의 이동 평균을 계산합니다.
즉, t 시점의 값은 t, t-1, ..., t-4까지의 평균입니다.
min_periods=1 덕분에 앞에 데이터가 부족할 때도 계산됨 (예: t=2면 2개만 평균).

| 시점 (t) | 값  | rolling 평균 (5)           |
| ------ | -- | ------------------------ |
| 0      | 10 | 10                       |
| 1      | 12 | (10+12)/2 = 11           |
| 2      | 9  | (10+12+9)/3 = 10.33      |
| 3      | 14 | (10+12+9+14)/4 = 11.25   |
| 4      | 13 | (10+12+9+14+13)/5 = 11.6 |
| 5      | 8  | (12+9+14+13+8)/5 = 11.2  |

2. Lag (Shift): shift(1)

값을 한 칸 뒤로 밀어 과거 값을 현재 위치로 가져옵니다.
t 시점에 t-1의 값을 넣는 구조.
시계열에서 **"직전 값"**을 참조할 때 자주 사용됩니다.

| 시점 (t) | 값  | lag\_1 |
| ------ | -- | ------ |
| 0      | 10 | NaN    |
| 1      | 12 | 10     |
| 2      | 9  | 12     |
| 3      | 14 | 9      |
| 4      | 13 | 14     |

3. Difference from Previous: diff()

현재 값에서 이전 값을 뺀 차이값을 구합니다.
즉, 변화량을 측정합니다. (변화 추이 파악)

| 시점 (t) | 값  | diff\_1 = 값\[t] - 값\[t-1] |
| ------ | -- | ------------------------- |
| 0      | 10 | NaN                       |
| 1      | 12 | 2                         |
| 2      | 9  | -3                        |
| 3      | 14 | 5                         |
| 4      | 13 | -1                        |

# rolling average와 diff는 노이즈 제거, 추세 파악에 매우 유용
'''

'\n1. Rolling Average: rolling(window=5, min_periods=1).mean()\n\n과거 5개의 값을 평균해서 현재 시점의 이동 평균을 계산합니다.\n즉, t 시점의 값은 t, t-1, ..., t-4까지의 평균입니다.\nmin_periods=1 덕분에 앞에 데이터가 부족할 때도 계산됨 (예: t=2면 2개만 평균).\n\n| 시점 (t) | 값  | rolling 평균 (5)           |\n| ------ | -- | ------------------------ |\n| 0      | 10 | 10                       |\n| 1      | 12 | (10+12)/2 = 11           |\n| 2      | 9  | (10+12+9)/3 = 10.33      |\n| 3      | 14 | (10+12+9+14)/4 = 11.25   |\n| 4      | 13 | (10+12+9+14+13)/5 = 11.6 |\n| 5      | 8  | (12+9+14+13+8)/5 = 11.2  |\n\n2. Lag (Shift): shift(1)\n\n값을 한 칸 뒤로 밀어 과거 값을 현재 위치로 가져옵니다.\nt 시점에 t-1의 값을 넣는 구조.\n시계열에서 **"직전 값"**을 참조할 때 자주 사용됩니다.\n\n| 시점 (t) | 값  | lag\\_1 |\n| ------ | -- | ------ |\n| 0      | 10 | NaN    |\n| 1      | 12 | 10     |\n| 2      | 9  | 12     |\n| 3      | 14 | 9      |\n| 4      | 13 | 14     |\n\n3. Difference from Previous: diff()\n\n현재 값에서 이전 값을 뺀 차이값을 구합니다.\n즉, 변화량을 측정합니다. (변화 추이 파악)\n\n| 시점 (t) | 값  | diff\\_1 = 값\\[t] - 값\\[t-1] |\n| ------ | -- | ------------------------- |\n| 0      | 10 | NaN                       |\n| 1      | 12 | 2                         |\n| 2      | 9  | -3                        |\n| 3      | 14 | 5                         |\n| 4      | 13 | -1                        |\n\n# rolling average와 diff는 노이즈 제거, 추세 파악에 매우 유용\n'

In [39]:
# X taf shape 확인
print("X_taf shape:", X_taf.shape)

X_taf shape: (1204883, 30)

In [40]:

taf_cols = list(X_taf.columns)

print(f"🧩 총 {len(taf_cols)}개의 TAF 컬럼:\n")

for i in range(0, len(taf_cols), 3):
    group = taf_cols[i:i+3]
    print(', '.join(group))

🧩 총 30개의 TAF 컬럼:

spin_efficiency_rolling_avg_5, spin_efficiency_lag_1, spin_efficiency_diff_1
speed_gap_rolling_avg_5, speed_gap_lag_1, speed_gap_diff_1
release_pos_angle_rolling_avg_5, release_pos_angle_lag_1, release_pos_angle_diff_1
plate_distance_rolling_avg_5, plate_distance_lag_1, plate_distance_diff_1
init_velocity_vector_rolling_avg_5, init_velocity_vector_lag_1, init_velocity_vector_diff_1
pitch_movement_vector_rolling_avg_5, pitch_movement_vector_lag_1, pitch_movement_vector_diff_1
speed_per_extension_rolling_avg_5, speed_per_extension_lag_1, speed_per_extension_diff_1
release_mechanics_profile_rolling_avg_5, release_mechanics_profile_lag_1, release_mechanics_profile_diff_1
vertical_spin_effect_rolling_avg_5, vertical_spin_effect_lag_1, vertical_spin_effect_diff_1
horizontal_spin_effect_rolling_avg_5, horizontal_spin_effect_lag_1, horizontal_spin_effect_diff_1

In [41]:
# X taf missing 확인

taf_dfs = {
    "X_taf": X_taf,
}

# 결측 있는 컬럼만 출력
for name, df in taf_dfs.items():
    missing_cols = df.columns[df.isnull().any()]
    if len(missing_cols) > 0:
        print(f"🔍 {name} has missing values in:")
        print(df[missing_cols].isnull().sum())
        print("-" * 40)
    else:
        print(f"✅ {name} has no missing values.")

🔍 X_taf has missing values in:
spin_efficiency_lag_1               1
spin_efficiency_diff_1              1
speed_gap_lag_1                     1
speed_gap_diff_1                    1
release_pos_angle_lag_1             1
release_pos_angle_diff_1            1
plate_distance_lag_1                1
plate_distance_diff_1               1
init_velocity_vector_lag_1          1
init_velocity_vector_diff_1         1
pitch_movement_vector_lag_1         1
pitch_movement_vector_diff_1        1
speed_per_extension_lag_1           1
speed_per_extension_diff_1          1
release_mechanics_profile_lag_1     1
release_mechanics_profile_diff_1    1
vertical_spin_effect_lag_1          1
vertical_spin_effect_diff_1         1
horizontal_spin_effect_lag_1        1
horizontal_spin_effect_diff_1       1
dtype: int64
----------------------------------------

In [112]:
# 결측값을 "아래 행의 값으로 채우는 방식" (backward fill)**
'''
첫 번째 행만 NaN인 경우가 대부분 (lag, diff 연산 때문)
모델 입력에 결측이 없어야 하므로, 가장 가까운 다음 값으로 복구함
'''

for df in [X_taf]:
    df.fillna(method="bfill", inplace=True)

In [113]:
# X taf missing 확인

taf_dfs = {
    "X_taf": X_taf,
}

# 결측 있는 컬럼만 출력
for name, df in taf_dfs.items():
    missing_cols = df.columns[df.isnull().any()]
    if len(missing_cols) > 0:
        print(f"🔍 {name} has missing values in:")
        print(df[missing_cols].isnull().sum())
        print("-" * 40)
    else:
        print(f"✅ {name} has no missing values.")

✅ X_taf has no missing values.

In [114]:
# taf feature 중 FE에 넣을 것 선택
selected_taf_cols = [
    'spin_efficiency_rolling_avg_5',
    'speed_gap_diff_1',
    'pitch_movement_vector_rolling_avg_5',
    'vertical_spin_effect_lag_1'
]

# 기존 df에 taf 집어넣기
X_FE[selected_taf_cols] = X_taf[selected_taf_cols] # DataFrame[col_list] = DataFrame2[col_list]

In [45]:
# 전체 feature column 목록 출력
print("X_FE shape:", X_FE.shape)
print()
print("🧩 전체 컬럼 리스트:")
for i in range(0, len(X_FE.columns), 5):
    print(X_FE.columns[i:i+5].tolist())

X_FE shape: (1204883, 52)

🧩 전체 컬럼 리스트:
['pitch_type', 'release_speed', 'release_pos_x', 'release_pos_z', 'zone']
['type', 'balls', 'strikes', 'pfx_x', 'pfx_z']
['plate_x', 'plate_z', 'outs_when_up', 'vx0', 'vy0']
['vz0', 'ax', 'ay', 'az', 'sz_top']
['sz_bot', 'effective_speed', 'release_spin_rate', 'release_extension', 'release_pos_y']
['at_bat_number', 'pitch_name', 'spin_axis', 'bat_score_diff', 'age_pit']
['age_bat', 'n_thruorder_pitcher', 'n_priorpa_thisgame_player_at_bat', 'pitcher_days_since_prev_game', 'batter_days_since_prev_game']
['api_break_z_with_gravity', 'api_break_x_arm', 'api_break_x_batter_in', 'arm_angle', 'game_type_R']
['stand_L', 'stand_R', 'p_throws_L', 'p_throws_R', 'if_fielding_alignment_Standard']
['if_fielding_alignment_Strategic', 'of_fielding_alignment_Standard', 'of_fielding_alignment_Strategic', 'spin_efficiency_rolling_avg_5', 'speed_gap_diff_1']
['pitch_movement_vector_rolling_avg_5', 'vertical_spin_effect_lag_1']

## 2-5 Feature Selection

In [46]:
#

## 2-6 Scailing

In [47]:
#

## 2-7 Filtering

### 2-7-1 Check

In [115]:
#
X = X_FE.copy()

# y, meta

In [116]:
# shape
shapes = {
    'X': X.shape,
    'y': y.shape,
    'meta': meta.shape,
}

# DataFrame으로 변환
df_shapes = pd.DataFrame(list(shapes.items()), columns=["Variable", "Shape"])

# 보기 좋게 출력
display(df_shapes)

  Variable          Shape
0        X  (1253816, 52)
1        y      (4296, 8)
2     meta  (1253816, 16)

In [117]:
# inning_topbot Count, Proportion 
def summarize_inning_topbot(meta_df, name):
    counts = meta_df['inning_topbot'].value_counts().to_dict()
    total = len(meta_df)
    result = []
    for label in ['Top', 'Bot']:  # 항상 Top, Bot 순서
        count = counts.get(label, 0)
        proportion = count / total * 100 if total > 0 else 0
        result.append({
            'Dataset': name,
            'inning_topbot': label,
            'Count': count,
            'Proportion (%)': round(proportion, 2)
        })
    return result

# 대상 메타 데이터셋
meta_sets = {
    'meta': meta,
}

# 통계 수집
inning_stats = []
for name, meta in meta_sets.items():
    inning_stats.extend(summarize_inning_topbot(meta, name))

# DataFrame으로 변환 및 pivot
df_inning_stats = pd.DataFrame(inning_stats)
display(df_inning_stats.pivot(index="Dataset", columns="inning_topbot", values=["Count", "Proportion (%)"]))

                  Count           Proportion (%)
inning_topbot       Bot       Top            Bot    Top
Dataset
meta           613644.0  640172.0          48.94  51.06

### 2-7-2 Filter

In [118]:
# mean, max, mode list

# 평균값(mean)을 대표값으로 삼는 연속형 수치 변수들
mean_cols = [
    # 투구 및 릴리스 관련 물리 변수들 – 평균 속도나 위치가 경기 스타일을 나타냄
    'release_speed', 'release_pos_x', 'release_pos_z', 'pfx_x', 'pfx_z',
    'plate_x', 'plate_z', 'vx0', 'vy0', 'vz0',
    'ax', 'ay', 'az', 'sz_top', 'sz_bot',
    'effective_speed', 'release_spin_rate', 'release_extension', 'release_pos_y', 'spin_axis',

    # 점수 관련 – 평균 점수 차가 경기 흐름을 반영
    'bat_score_diff',

    # 브레이킹/구질 관련 파생 변수 – 평균 곡선 형태를 반영
    'api_break_z_with_gravity', 'api_break_x_arm', 'api_break_x_batter_in', 'arm_angle',

    # 선수 나이 및 이전 경기 이력 – 평균으로 부드럽게 반영
    'age_pit', 'age_bat', 'pitcher_days_since_prev_game', 'batter_days_since_prev_game',

    # 범주형 인코딩 결과 – 전체 평균으로 경기 경향성 반영
    'game_type_R', 'stand_L', 'stand_R', 'p_throws_L', 'p_throws_R',
    'if_fielding_alignment_Standard', 'if_fielding_alignment_Strategic',
    'of_fielding_alignment_Standard', 'of_fielding_alignment_Strategic'
]


# 최대값(max)을 대표값으로 삼는 변수들
max_cols = [
    # at-bat 또는 투구 순서 – 경기 내에서 가장 깊이 갔던 상황을 반영
    'at_bat_number',

    # 투수/타자의 순서나 반복 상황 – 최대 반복 정도를 경기 요약으로 사용
    'n_thruorder_pitcher', 'n_priorpa_thisgame_player_at_bat'
]


# 최빈값(mode)을 대표값으로 삼는 범주형 변수들
mode_cols = [
    # 구종, 스트라이크존, 판정 등 – 가장 자주 등장한 항목이 특징을 잘 나타냄
    'pitch_type', 'zone', 'type', 'balls', 'strikes',
    'outs_when_up', 'pitch_name'
]

# 안전한 mode 추출 함수
def safe_mode(series):
    result = mode(series, nan_policy='omit')

    # scipy 버전에 따라 result.mode와 result.count가 스칼라일 수 있음
    mode_val = getattr(result, "mode", None)
    count_val = getattr(result, "count", None)

    # 둘 다 리스트나 배열이면 → 일반적인 처리
    if hasattr(mode_val, '__len__') and len(mode_val) > 0:
        return mode_val[0]
    # 스칼라일 경우
    elif np.isscalar(mode_val):
        return mode_val
    # 그 외 (빈 값이거나 에러 상황)
    else:
        return np.nan


# 기존 목록을 set으로 바꿔 중복 방지
mean_cols_set = set(mean_cols)
max_cols_set = set(max_cols)
mode_cols_set = set(mode_cols)

# 추적용 리스트
new_mean, new_max, new_mode = [], [], []


# taf 추가
for col in selected_taf_cols:
    if "rolling_avg" in col:
        if col not in mean_cols_set:
            mean_cols_set.add(col)
            new_mean.append(col)
    elif "lag" in col:
        if col not in max_cols_set:
            max_cols_set.add(col)
            new_max.append(col)
    elif "diff" in col:
        if col not in mode_cols_set:
            mode_cols_set.add(col)
            new_mode.append(col)

# 리스트로 다시 변환
mean_cols = list(mean_cols_set)
max_cols = list(max_cols_set)
mode_cols = list(mode_cols_set)

orig_mean_count = len(mean_cols_set) - len(new_mean)
orig_max_count = len(max_cols_set) - len(new_max)
orig_mode_count = len(mode_cols_set) - len(new_mode)

# 출력
print(f"✅ {len(new_mean)} TAF features added to mean_cols:", new_mean)
print(f"✅ {len(new_max)} TAF features added to max_cols:", new_max)
print(f"✅ {len(new_mode)} TAF features added to mode_cols:", new_mode)

print("\n🔢 최종 feature 수 요약")
print(f"All cols: {orig_mean_count+ orig_max_count + orig_mode_count} → {len(mean_cols + max_cols + mode_cols)}(taf)")
print("----------------------------")
print(f"mean_cols: {orig_mean_count} → {len(mean_cols)}(taf)")
print(f"max_cols: {orig_max_count} → {len(max_cols)}(taf)")
print(f"mode_cols: {orig_mode_count} → {len(mode_cols)}(taf)")

✅ 2 TAF features added to mean_cols: ['spin_efficiency_rolling_avg_5', 'pitch_movement_vector_rolling_avg_5']
✅ 1 TAF features added to max_cols: ['vertical_spin_effect_lag_1']
✅ 1 TAF features added to mode_cols: ['speed_gap_diff_1']

🔢 최종 feature 수 요약
All cols: 48 → 52(taf)
----------------------------
mean_cols: 38 → 40(taf)
max_cols: 3 → 4(taf)
mode_cols: 7 → 8(taf)

In [119]:
# 5-2. is_pitch

pitch_features = [
    'release_speed',  # 투구 속도 (투수 릴리스 시점)
    'release_pos_x',  # 투수 릴리스 위치 (좌우)
    'release_pos_z',  # 투수 릴리스 위치 (높이)
    'release_pos_y',  # 투수 릴리스 위치 (홈과의 거리)
    'pfx_x',  # 투구의 좌우 변화량
    'pfx_z',  # 투구의 상하 변화량
    'vx0',  # 투구 초기 속도 x축 성분
    'vy0',  # 투구 초기 속도 y축 성분
    'vz0',  # 투구 초기 속도 z축 성분
    'ax',  # 투구 가속도 x축
    'ay',  # 투구 가속도 y축
    'az',  # 투구 가속도 z축
    'effective_speed',  # 타자가 느끼는 실질적인 공의 속도
    'release_spin_rate',  # 릴리스 순간의 회전수
    'release_extension',  # 릴리스 지점과 홈플레이트 사이 거리
    'spin_axis',  # 공의 회전축 (구질의 방향성)
    'arm_angle',  # 투수 팔의 릴리스 각도
    'age_pit',  # 투수 나이
    'pitcher_days_since_prev_game',  # 투수의 마지막 등판 이후 휴식일 수
    'api_break_z_with_gravity',  # 중력 포함 투구 낙폭 (낙차)
    'api_break_x_arm',  # 투수 기준 좌우 변화량
    'p_throws_L',  # 투수가 왼손잡이인지 여부 (One-hot)
    'p_throws_R',  # 투수가 오른손잡이인지 여부 (One-hot)
    'game_type_R',  # 경기 타입이 정규시즌(R)인지 여부 (정규 메타정보)
    'n_thruorder_pitcher',  # 해당 투수가 타자 라인업을 몇 번째 도는 중인지
    'if_fielding_alignment_Standard',  # 내야 수비 스탠다드 여부
    'if_fielding_alignment_Strategic',  # 내야 수비 전략적 배치 여부
    'of_fielding_alignment_Standard',  # 외야 수비 스탠다드 여부
    'of_fielding_alignment_Strategic'  # 외야 수비 전략적 배치 여부
]

swing_features = [
    'plate_x',  # 공이 홈플레이트 기준 좌우 어디를 통과했는지
    'plate_z',  # 공이 홈플레이트 기준 어느 높이를 통과했는지
    'balls',  # 현재 볼 카운트
    'strikes',  # 현재 스트라이크 카운트
    'outs_when_up',  # 타석 시점 아웃 카운트
    'bat_score_diff',  # 타석 시점 점수차 (타자 팀 기준)
    'api_break_x_batter_in',  # 타자 기준으로 몸쪽으로 휘는 정도
    'age_bat',  # 타자 나이
    'batter_days_since_prev_game',  # 타자의 마지막 출전 이후 휴식일 수
    'stand_L',  # 타자가 왼손잡이인지 여부 (One-hot)
    'stand_R',  # 타자가 오른손잡이인지 여부 (One-hot)
    'at_bat_number',  # 이 경기에서의 타석 번호
    'n_priorpa_thisgame_player_at_bat',  # 이 경기에서의 타자의 이전 타석 수
    'pitch_type',  # 투구 타입 코드 (ex. 'FF' 등)
    'zone',  # 스트라이크 존 번호 (1~14)
    'type',  # 결과 타입 (B: 볼, S: 스트라이크, X: 인플레이)
    'pitch_name',  # 구질 명칭 (ex. 4-Seam Fastball)
    'sz_top',  # 타자 기준 스트라이크 존 상단
    'sz_bot'   # 타자 기준 스트라이크 존 하단
]
'''
taf_pitch_cols = [
    'spin_efficiency_rolling_avg_5', 'spin_efficiency_lag_1', 'spin_efficiency_diff_1',
    'speed_gap_rolling_avg_5', 'speed_gap_lag_1', 'speed_gap_diff_1',
    'release_pos_angle_rolling_avg_5', 'release_pos_angle_lag_1', 'release_pos_angle_diff_1',
    'init_velocity_vector_rolling_avg_5', 'init_velocity_vector_lag_1', 'init_velocity_vector_diff_1',
    'pitch_movement_vector_rolling_avg_5', 'pitch_movement_vector_lag_1', 'pitch_movement_vector_diff_1',
    'speed_per_extension_rolling_avg_5', 'speed_per_extension_lag_1', 'speed_per_extension_diff_1',
    'release_mechanics_profile_rolling_avg_5', 'release_mechanics_profile_lag_1', 'release_mechanics_profile_diff_1',
    'vertical_spin_effect_rolling_avg_5', 'vertical_spin_effect_lag_1', 'vertical_spin_effect_diff_1',
    'horizontal_spin_effect_rolling_avg_5', 'horizontal_spin_effect_lag_1', 'horizontal_spin_effect_diff_1'
]
taf_swing_cols = [
    'plate_distance_rolling_avg_5', 'plate_distance_lag_1', 'plate_distance_diff_1'
]
'''

# pitch/swing 구분 키워드 정의 (기준 키워드)
pitch_keywords = [
    'spin_efficiency', 'speed_gap', 'release_pos_angle',
    'init_velocity_vector', 'pitch_movement_vector',
    'speed_per_extension', 'release_mechanics_profile',
    'vertical_spin_effect', 'horizontal_spin_effect'
]
swing_keywords = ['plate_distance']

# selected_taf_cols를 기준으로 분류
taf_pitch_cols = [col for col in selected_taf_cols if any(key in col for key in pitch_keywords)]
taf_swing_cols = [col for col in selected_taf_cols if any(key in col for key in swing_keywords)]

# pitch/swing feature 확장
pitch_features += taf_pitch_cols
swing_features += taf_swing_cols

# 확인
print(f"📌 pitch_features 총 개수: {len(pitch_features)}")
print(f"📌 swing_features 총 개수: {len(swing_features)}")

print("\n🎯 추가된 TAF pitch features:")
print(taf_pitch_cols)

print("\n🎯 추가된 TAF swing features:")
print(taf_swing_cols)

📌 pitch_features 총 개수: 33
📌 swing_features 총 개수: 19

🎯 추가된 TAF pitch features:
['spin_efficiency_rolling_avg_5', 'speed_gap_diff_1', 'pitch_movement_vector_rolling_avg_5', 'vertical_spin_effect_lag_1']

🎯 추가된 TAF swing features:
[]

In [120]:
# mean, max mode list apply function
def summarize_features(group):
    summary = {}

    for col in mean_cols:
        summary[col] = group[col].mean()
    for col in max_cols:
        summary[col] = group[col].max()
    for col in mode_cols:
        summary[col] = safe_mode(group[col])

    return pd.Series(summary)

In [121]:
def filter_dataset(X, meta):
    # X <- game_pk, inning_topbot
    X_ = X.copy().assign(game_pk=meta['game_pk'], inning_topbot=meta['inning_topbot'])
    
    # 1. groupby game_pk
    # 2. groupby inning_topbot
    grouped = X_.groupby(['game_pk', 'inning_topbot'], group_keys=False) # groupby method chaining
    
    # 3. apply
    grouped = grouped.apply(summarize_features).reset_index()
    # XGBC 의 경우 groupby 후 apply를 할 때 "행의 순서"가 최종 결과에 영향을 미치진 않는다. 어차피 압축됨
    # 하지만 순서 필요하면 groupby(['game_pk', 'inning', 'inning_topbot'])
    
    # inning_topbot 에서 알파벳 정렬 상 Bot이 Top 보다 먼저 나온다. Top Bot 순서로 바꿔야 시계열을 더 잘 지킨것
    grouped['inning_topbot'] = pd.Categorical(grouped['inning_topbot'], categories=['Top', 'Bot'], ordered=True)
    grouped = grouped.sort_values(by=['game_pk', 'inning_topbot']).reset_index(drop=True)
    
    # apply display
    print("groupby game_pk, inning_topbot and apply")
    display(grouped)
    
    # 2. pivot → Top/Bottom 결합
    pivoted = grouped.pivot(index='game_pk', columns='inning_topbot')
    '''
    index='game_pk': 각 경기를 하나의 행으로 만들고
    columns='inning_topbot': 'Top'과 'Bot'을 열의 계층 이름(level)으로 바꿔서 각 feature가 두 버전으로 나뉘게 합니다.
    이 작업 후 결과는 멀티컬럼(MultiIndex column)을 가지는 DataFrame입니다:
    game_pk	(release_speed, Top)	(release_speed, Bot)	...
    즉, 열이 튜플로 구성된 **계층형 열 구조 (MultiIndex)**입니다.
    '''

    pivoted.columns = [f"{col}_{tb.lower()}" for col, tb in pivoted.columns]
    '''
    pivoted.columns은 MultiIndex 형태입니다: 예를 들어 (release_speed, Top) 같은 쌍이 있음.
    이걸 우리가 원하는 형태: release_speed_top, release_speed_bot 으로 바꾸는 코드입니다.
    .lower()는 소문자화
    '''
    
    # ✅ game_pk를 일반 컬럼으로 추가
    pivoted.reset_index(inplace=True)  # 이제 game_pk가 컬럼으로 들어감
    
    # pivoted display
    print("pivot")
    display(pivoted)
    
    # sample 순서를 Top Bot으로 바꾼 것과 다르게 feature 에서는 top bot 순서 딱히 상관 x
    
    X_filtered = pivoted
    
    
    
    # meta: 경기 단위로 요약 (마지막 row)
    meta_filtered = (
        meta
        .groupby('game_pk', group_keys=False)
        .last()
        .reset_index(drop=False)
    )
    # 압축시 불필요한 컬럼 제거
    drop_meta_cols = ['inning', 'inning_topbot', 'pitch_number', 'batter', 'pitcher', 'events']
    meta_filtered.drop(columns=drop_meta_cols, errors='ignore', inplace=True)
    
    return X_filtered, meta_filtered

In [122]:
X, meta = filter_dataset(X, meta)

groupby game_pk, inning_topbot and apply

,game_pk,inning_topbot,vy0,release_pos_z,pitch_movement_vector_rolling_avg_5,of_fielding_alignment_Strategic,vz0,plate_x,release_extension,plate_z,...,vertical_spin_effect_lag_1,n_thruorder_pitcher,type,pitch_name,outs_when_up,pitch_type,zone,balls,speed_gap_diff_1,strikes
0,744795,Top,-129.345981,5.819236,1.193060,0.000000,-3.971699,0.230625,6.581250,2.424097,...,354.24,3.0,1.0,0.0,0.0,6.0,2.0,0.0,0.3,0.0
1,744795,Bot,-130.755653,5.708963,1.179294,0.000000,-3.491576,-0.122074,6.328148,2.330222,...,339.20,2.0,1.0,0.0,0.0,6.0,3.0,0.0,-0.2,0.0
2,744796,Top,-128.002059,6.164599,1.017220,0.000000,-4.650227,0.162190,6.552555,2.194088,...,326.04,3.0,1.0,12.0,0.0,14.0,3.0,0.0,0.1,0.0
3,744796,Bot,-128.486845,6.201439,1.132137,0.000000,-4.190004,-0.085530,6.741667,2.621515,...,341.04,3.0,1.0,0.0,0.0,6.0,5.0,0.0,0.0,0.0
4,744797,Top,-125.695094,5.328992,1.154044,0.000000,-2.782262,-0.089767,6.804651,2.119612,...,360.40,2.0,1.0,0.0,2.0,6.0,3.0,0.0,-0.6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8587,778538,Bot,-126.379546,5.702086,1.188817,0.176471,-3.033586,-0.117005,6.021925,2.341390,...,359.48,2.0,0.0,0.0,2.0,6.0,3.0,0.0,0.0,0.0
8588,778539,Top,-127.203668,5.759837,1.169279,0.010870,-3.311047,-0.126739,6.060326,2.281413,...,359.52,2.0,1.0,0.0,0.0,6.0,4.0,0.0,0.4,0.0
8589,778539,Bot,-129.440444,5.654333,1.175799,0.055556,-3.806120,-0.256611,6.785556,2.305222,...,393.76,3.0,1.0,0.0,0.0,6.0,3.0,0.0,-0.3,0.0
8590,778540,Top,-132.626381,5.541148,1.302451,0.000000,-2.838014,0.561066,6.157377,2.485082,...,351.45,3.0,1.0,0.0,0.0,6.0,2.0,0.0,0.0,0.0
8591,778540,Bot,-130.246972,6.513185,1.219617,0.044444,-5.655766,0.115037,6.327407,2.356963,...,354.90,3.0,1.0,0.0,1.0,6.0,4.0,0.0,-0.3,0.0

pivot

,game_pk,vy0_top,vy0_bot,release_pos_z_top,release_pos_z_bot,pitch_movement_vector_rolling_avg_5_top,pitch_movement_vector_rolling_avg_5_bot,of_fielding_alignment_Strategic_top,of_fielding_alignment_Strategic_bot,vz0_top,...,pitch_type_top,pitch_type_bot,zone_top,zone_bot,balls_top,balls_bot,speed_gap_diff_1_top,speed_gap_diff_1_bot,strikes_top,strikes_bot
0,744795,-129.345981,-130.755653,5.819236,5.708963,1.193060,1.179294,0.000000,0.000000,-3.971699,...,6.0,6.0,2.0,3.0,0.0,0.0,0.3,-0.2,0.0,0.0
1,744796,-128.002059,-128.486845,6.164599,6.201439,1.017220,1.132137,0.000000,0.000000,-4.650227,...,14.0,6.0,3.0,5.0,0.0,0.0,0.1,0.0,0.0,0.0
2,744797,-125.695094,-127.194726,5.328992,5.889042,1.154044,1.142301,0.000000,0.000000,-2.782262,...,6.0,13.0,3.0,3.0,0.0,0.0,-0.6,0.0,0.0,0.0
3,744798,-129.999453,-128.917215,5.912917,5.507407,1.363566,1.361110,0.000000,0.000000,-4.240545,...,6.0,6.0,4.0,4.0,0.0,0.0,-0.3,-0.1,0.0,2.0
4,744799,-133.863275,-132.935662,5.919333,5.388582,1.251558,1.212474,0.000000,0.000000,-4.755567,...,6.0,6.0,3.0,4.0,0.0,0.0,0.2,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4291,778536,-130.047755,-131.708985,5.623774,6.006752,1.249342,1.287257,0.081761,0.000000,-3.407026,...,6.0,6.0,4.0,4.0,0.0,0.0,-0.3,0.2,0.0,0.0
4292,778537,-128.246265,-131.922609,5.781395,5.731494,1.061392,1.103267,0.000000,0.000000,-2.669803,...,14.0,6.0,2.0,4.0,0.0,0.0,0.0,-0.2,0.0,0.0
4293,778538,-129.560985,-126.379546,5.968000,5.702086,1.194171,1.188817,0.024242,0.176471,-3.598756,...,6.0,6.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
4294,778539,-127.203668,-129.440444,5.759837,5.654333,1.169279,1.175799,0.010870,0.055556,-3.311047,...,6.0,6.0,4.0,3.0,0.0,0.0,0.4,-0.3,0.0,0.0
4295,778540,-132.626381,-130.246972,5.541148,6.513185,1.302451,1.219617,0.000000,0.044444,-2.838014,...,6.0,6.0,2.0,4.0,0.0,0.0,0.0,-0.3,0.0,0.0

In [123]:
# sample sort by meta game date

def sort_by_meta_date(X, y, meta):
    # 1. meta를 game_date 기준으로 정렬
    meta_sorted = meta.sort_values("game_date").reset_index(drop=False)

    # 2. meta_sorted의 game_pk 순서로 X와 y 정렬
    game_pk_order = meta_sorted["game_pk"].tolist()

    # X, y에서 game_pk 컬럼 기준으로 정렬
    X_sorted = X.set_index("game_pk").loc[game_pk_order].reset_index()
    y_sorted = y.set_index("game_pk").loc[game_pk_order].reset_index()
    
    # 3. meta_sorted에서 필요한 열만 추출
    meta_info = meta_sorted[["game_pk", "date_str", "match_id"]]

    # 4. X_sorted에 병합
    X_sorted = X_sorted.merge(meta_info, on="game_pk", how="left")



    return X_sorted, y_sorted, meta_sorted



X, y, meta = sort_by_meta_date(X, y, meta)

In [57]:
'''

# 저장할 파일명
excel_path = INDICATOR_PATH + "2-7_X_y_meta_samples.xlsx"

# 상위 10개 샘플 추출
X_sample = X.copy()
y_sample = y.copy()
meta_sample = meta.copy()

# Excel로 저장 (index 포함 + index 이름 지정)
with pd.ExcelWriter(excel_path) as writer:
    
    X_sample.to_excel(writer, sheet_name="X_Sample", index=True)
    y_sample.to_excel(writer, sheet_name="y_Sample", index=True)
    meta_sample.to_excel(writer, sheet_name="meta_Sample", index=True)

print(f"✅ X, y, meta 상위 10개 샘플 (index 포함, game_pk 라벨) Excel 저장 완료 → {excel_path}")

'''

'\n\n# 저장할 파일명\nexcel_path = INDICATOR_PATH + "2-7_X_y_meta_samples.xlsx"\n\n# 상위 10개 샘플 추출\nX_sample = X.copy()\ny_sample = y.copy()\nmeta_sample = meta.copy()\n\n# Excel로 저장 (index 포함 + index 이름 지정)\nwith pd.ExcelWriter(excel_path) as writer:\n    \n    X_sample.to_excel(writer, sheet_name="X_Sample", index=True)\n    y_sample.to_excel(writer, sheet_name="y_Sample", index=True)\n    meta_sample.to_excel(writer, sheet_name="meta_Sample", index=True)\n\nprint(f"✅ X, y, meta 상위 10개 샘플 (index 포함, game_pk 라벨) Excel 저장 완료 → {excel_path}")\n\n'

In [58]:
# shape
shape_data = {
    "Set": [
        "X",
        "y",
        "meta",
    ],
    "Shape": [
        X.shape,
        y.shape,
        meta.shape,
    ]
}

shape_df = pd.DataFrame(shape_data)
display(shape_df)

    Set        Shape
0     X  (4130, 107)
1     y    (4130, 8)
2  meta   (4130, 11)

In [124]:
# predict_match_dict 는 예측해야 하는 매치의 리스트임
# predict_match_dict 가 정해지면 그 리스트에 대해 매번 train, valid, test 를 산정

# 한국 8/8 11pm (미국 8/8 9am) -> 미국 8/8 7pm 경기 예측 가능

# pred_match_dict 데이터 불러오기
with open(pred_json_path, "r", encoding="utf-8") as f:
    pred_match_dict = json.load(f)

In [ ]:
import json, os, datetime as dt

def build_fv_plan_jsonl(pred_match_dict,
                        X, meta,
                        window,
                        out_path,
                        cutoff_inclusive):
    """
    pred_match_dict: {"250807": ["MIA@ATL", ...], ...}
    X:  pivot 이후의 특징 DF (game_pk, date_str, match_id 포함)
    meta: (game_pk, game_date, home_team, away_team 포함)
    """

    # 준비: 경기 메타 한곳으로 (검색용)
    gi = (meta[['game_pk','game_date','home_team','away_team']]
          .copy())
    gi['date_str'] = pd.to_datetime(gi['game_date']).dt.strftime('%y%m%d')
    gi['match_id'] = gi['away_team'] + '@' + gi['home_team']

    # 소스 스냅샷(디버그용)
    src_rows = len(X)
    src_min = pd.to_datetime(meta['game_date']).min()
    src_max = pd.to_datetime(meta['game_date']).max()

    # 출력 폴더
    Path(os.path.dirname(out_path) or ".").mkdir(parents=True, exist_ok=True)

    n_lines = 0
    with open(out_path, "w", encoding="utf-8") as fw:
        for pred_date, matches in pred_match_dict.items():
            # 컷오프 날짜 파싱
            cutoff_dt = dt.datetime.strptime(pred_date, "%y%m%d").date()
            if cutoff_inclusive:
                date_filter = gi['game_date'].dt.date <= cutoff_dt
            else:
                date_filter = gi['game_date'].dt.date <  cutoff_dt

            for m in matches:
                try:
                    away, home = m.split("@")
                except ValueError:
                    print(f"⚠️ match_id 파싱 실패: {m} (건너뜀)")
                    continue

                # 최근 경기 추출: 역할 고정(away는 away로, home은 home으로)
                away_hist = (gi[(gi['away_team']==away) & date_filter]
                             .sort_values('game_date', ascending=False)
                             .head(window))
                home_hist = (gi[(gi['home_team']==home) & date_filter]
                             .sort_values('game_date', ascending=False)
                             .head(window))

                def pack_rows(df):
                    # 최신순으로 1..k 순번
                    out = []
                    for idx, (_, r) in enumerate(df.reset_index().iterrows(), start=1):
                        out.append({
                            "order": idx,                    # 1 = 가장 최근
                            "game_pk": int(r['game_pk']),
                            "date_str": r['date_str'],
                            "match_id": r['match_id'],
                        })
                    return out

                away_games_packed = pack_rows(away_hist)
                home_games_packed = pack_rows(home_hist)

                # 가장 오래된 경기 날짜 찾기
                all_dates = []
                if away_games_packed:
                    all_dates.extend([g["date_str"] for g in away_games_packed])
                if home_games_packed:
                    all_dates.extend([g["date_str"] for g in home_games_packed])

                if all_dates:
                    oldest_str = min(all_dates)  # 가장 오래된 날짜
                    oldest_dt = dt.datetime.strptime(oldest_str, "%y%m%d").date()
                    train_available_date = (oldest_dt - dt.timedelta(days=1)).strftime("%y%m%d")
                else:
                    train_available_date = None

                entry = {
                    "pred_date": pred_date,
                    "match_id": m,
                    "window": window,
                    "away_team": away,
                    "home_team": home,
                    "away_games": away_games_packed,
                    "home_games": home_games_packed,
                    "train_available_date": train_available_date,  # ✅ 추가됨
                    "cutoff": pred_date,
                    "cutoff_inclusive": cutoff_inclusive,
                    "generated_at": dt.datetime.utcnow().isoformat(timespec="seconds") + "Z",
                    "source_snapshot": {
                        "rows": int(src_rows),
                        "min_date": str(src_min.date()) if pd.notna(src_min) else None,
                        "max_date": str(src_max.date()) if pd.notna(src_max) else None,
                    }
                }

                # 부족하면 메모 남기기
                if len(entry["away_games"]) < window or len(entry["home_games"]) < window:
                    entry["note"] = {
                        "away_found": len(entry["away_games"]),
                        "home_found": len(entry["home_games"]),
                        "window": window
                    }

                fw.write(json.dumps(entry, ensure_ascii=False) + "\n")
                n_lines += 1

    print(f"✅ JSONL 생성 완료: {out_path} (lines: {n_lines})")



'''
build_fv_plan_jsonl(
    pred_match_dict=pred_match_dict,
    X=X, meta=meta,
    window=3,
    out_path="pred_match_dict.jsonl",
    cutoff_inclusive=False,   # 예측일 이전 경기만 사용
)
'''

✅ JSONL 생성 완료: pred_match_dict.jsonl (lines: 1163)

In [ ]:
# json 형식 보기 편하게 변경


'''
jsonl_path = "pred_match_dict.jsonl"
pretty_jsonl_path = "pretty_pred_match_dict.jsonl"

with open(jsonl_path, "r", encoding="utf-8") as f_in, \
     open(pretty_jsonl_path, "w", encoding="utf-8") as f_out:
    for line in f_in:
        obj = json.loads(line)
        f_out.write(json.dumps(obj, indent=2, ensure_ascii=False) + "\n")
'''

In [62]:
'''
< 재료 >
	Set	Shape
0	X	(4115, 107)
1	y	(4115, 8)
2	meta	(4115, 11)


pretty_pred_match_dict.jsonl
'''

'\n< 재료 >\n\tSet\tShape\n0\tX\t(4115, 107)\n1\ty\t(4115, 8)\n2\tmeta\t(4115, 11)\n\n\npretty_pred_match_dict.jsonl\n'

In [63]:
# X 를 날짜로 자름 (원하는 부분부터 사용)

In [64]:
#--------------- 아래부터는 기능 모듈화, 개별 매치로 처리 후 반복 ---------------

In [127]:
# pred_match_dict.jsonl 의 줄 수 세기
file_path = "pred_match_dict.jsonl"

with open(file_path, "r") as f:
    num_matches = sum(1 for _ in f)

print("num_matches (매치 수) : ", num_matches)



def split_counts_by_ratio(n, ratios=(0.8, 0.1, 0.1)):
    r_train, r_valid, r_test = ratios
    n_train = int(n * r_train)
    n_valid = int(n * r_valid)
    n_test  = int(n * r_test)
    remain  = n - (n_train + n_valid + n_test)
    n_test += remain
    return n_train, n_valid, n_test

def to_int_date(s: str) -> int:
    """
    date_str (예: '250520') → 정수(YYYYMMDD) 변환
    앞의 두 자리가 연도(25 → 2025)라는 전제를 둡니다.
    """
    if pd.isna(s):
        return None
    s = str(s)
    if len(s) == 6:  # YYMMDD 형식
        return int("20" + s)  # 2025XXYY
    elif len(s) == 8:  # YYYYMMDD 형식
        return int(s)
    else:
        raise ValueError(f"지원하지 않는 date_str 형식: {s}")

# DataFrame 요약 함수
def summarize_df(df, head=10, tail=10):
    """앞/뒤 head, tail 행만 남기고 중간에 구분 행 추가"""
    if len(df) <= head + tail:
        return df
    top = df.head(head)
    bottom = df.tail(tail)
    sep = pd.DataFrame([["..."] * len(df.columns)], columns=df.columns)
    return pd.concat([top, sep, bottom], ignore_index=True)

# 모델 입력 전에 X에 "game_pk", "date_str", "match_id", "date_int" 제거
META_COLS = ["game_pk", "date_str", "match_id", "date_int"]     # X에서 제거할 메타 컬럼
TARGET_COL = "label"                                            # y에서 사용할 타깃 컬럼

def align_xy(
    X_slice: pd.DataFrame,
    y_full: pd.DataFrame,
    *,
    stage: str,
    meta_cols = META_COLS,
    target_col = TARGET_COL,
):

    # 1) 상세 비교 테이블 만들기
    df_detail = pd.DataFrame({
        "X_date_str": X_slice["date_str"],
        "X_match_id": X_slice["match_id"],
        "X_game_pk":  X_slice["game_pk"],
        
        "y_date_str": y_full["date_str"],
        "y_match_id": y_full["match_id"],
        "y_game_pk":  y_full["game_pk"],
        "label":      y_full["label"],
    })


    # 3-1) X에서 메타 컬럼 제거 → 순수 피처만 남기기
    # 모델 입력 전에 X에 "game_pk", "date_str", "match_id", "date_int" 제거
    X_feat = X_slice.drop(columns=meta_cols, errors="ignore").copy()
    
    # X의 col 순서를 변수로 저장
    feature_order = X_feat.columns.tolist()
    
    

    # 3-2) y 벡터 추출
    # "label" 만 남기기
    y_vec = y_full[target_col].to_numpy()

    return X_feat, y_vec, df_detail, feature_order

def _ensure_dir(p):
    d = os.path.dirname(p)
    if d and not os.path.exists(d):
        os.makedirs(d, exist_ok=True)

def find_best_threshold(y_true, proba, lo=0.30, hi=0.70, step=0.01):
    thresholds = np.arange(lo, hi, step)
    best_t, best_f1 = 0.5, -1.0
    for t in thresholds:
        y_pred = (proba >= t).astype(int)
        f1 = f1_score(y_true, y_pred, zero_division=0)
        if f1 > best_f1:
            best_t, best_f1 = t, f1
    return float(best_t), float(best_f1)

def save_confmat(y_true, y_pred, title, out_png):
    cm = confusion_matrix(y_true, y_pred)

    fig, ax = plt.subplots(figsize=(4,4))
    # 흰 배경 고정
    fig.patch.set_facecolor('white')
    ax.set_facecolor('white')

    # 밝은 컬러맵 사용
    im = ax.imshow(cm, interpolation='nearest', cmap='Blues')

    ax.set_title(title)
    ax.set_xlabel("Predicted label")
    ax.set_ylabel("True label")
    ax.set_xticks([0, 1]); ax.set_yticks([0, 1])

    # 셀 숫자 주석(검정 글자)
    for (i, j), v in np.ndenumerate(cm):
        ax.text(j, i, str(v), ha='center', va='center', color='black')

    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    plt.tight_layout()

    _ensure_dir(out_png)
    plt.savefig(out_png, dpi=150, facecolor=fig.get_facecolor(), edgecolor='none')
    plt.close(fig)


def save_calibration_curve(y_true, probas_dict, out_png):
    fig, ax = plt.subplots(figsize=(7,6))
    for name, proba in probas_dict.items():
        prob_true, prob_pred = calibration_curve(y_true, proba, n_bins=10)
        ax.plot(prob_pred, prob_true, marker='o', label=name)
    ax.plot([0,1],[0,1],'--',label='Perfect')
    ax.set_xlabel("Mean predicted probability"); ax.set_ylabel("Fraction of positives")
    ax.set_title("Calibration Curves (Validation)"); ax.grid(True); ax.legend()
    plt.tight_layout()
    _ensure_dir(out_png); plt.savefig(out_png, dpi=150); plt.close(fig)

def save_roc(y_true, probas_dict, out_png):
    fig, ax = plt.subplots(figsize=(7,6))
    for name, proba in probas_dict.items():
        auc = roc_auc_score(y_true, proba)
        fpr, tpr, _ = roc_curve(y_true, proba)
        ax.plot(fpr, tpr, label=f"{name} (AUC={auc:.3f})")
    ax.plot([0,1],[0,1],'--',label='Random')
    ax.set_xlabel("False Positive Rate"); ax.set_ylabel("True Positive Rate")
    ax.set_title("ROC (Validation)"); ax.grid(True); ax.legend()
    plt.tight_layout()
    _ensure_dir(out_png); plt.savefig(out_png, dpi=150); plt.close(fig)

# ----------------------------- 5) new 합성
"""
임시로 new에서 "game_pk", "date_str", "match_id" 떼어냄
합성시에 들어가면 안 되기 때문
"""
    
# 1. summarize
# mean, max, mode col -> top/bot 확장
def expand_topbot(base_cols):
    return [f"{col}_top" for col in base_cols] + [f"{col}_bot" for col in base_cols]

mean_cols_topbot = expand_topbot(mean_cols)
max_cols_topbot = expand_topbot(max_cols)
mode_cols_topbot = expand_topbot(mode_cols)

print("mean_cols_topbot len : " + str(len(mean_cols_topbot)))
print("max_cols_topbot len : " + str(len(max_cols_topbot)))
print("mode_cols_topbot len : " + str(len(mode_cols_topbot)))

def summarize_prediction_feature(group: pd.DataFrame) -> pd.Series:
    summary = {}

    for col in mean_cols_topbot:
        summary[col] = group[col].mean()

    for col in max_cols_topbot:
        summary[col] = group[col].max()

    for col in mode_cols_topbot:
        summary[col] = safe_mode(group[col])  # 기존에 정의한 mode 함수 사용

    return pd.Series(summary)
    
# 2. is_pitch
pitch_features = [
    'release_speed',  # 투구 속도 (투수 릴리스 시점)
    'release_pos_x',  # 투수 릴리스 위치 (좌우)
    'release_pos_z',  # 투수 릴리스 위치 (높이)
    'release_pos_y',  # 투수 릴리스 위치 (홈과의 거리)
    'pfx_x',  # 투구의 좌우 변화량
    'pfx_z',  # 투구의 상하 변화량
    'vx0',  # 투구 초기 속도 x축 성분
    'vy0',  # 투구 초기 속도 y축 성분
    'vz0',  # 투구 초기 속도 z축 성분
    'ax',  # 투구 가속도 x축
    'ay',  # 투구 가속도 y축
    'az',  # 투구 가속도 z축
    'effective_speed',  # 타자가 느끼는 실질적인 공의 속도
    'release_spin_rate',  # 릴리스 순간의 회전수
    'release_extension',  # 릴리스 지점과 홈플레이트 사이 거리
    'spin_axis',  # 공의 회전축 (구질의 방향성)
    'arm_angle',  # 투수 팔의 릴리스 각도
    'age_pit',  # 투수 나이
    'pitcher_days_since_prev_game',  # 투수의 마지막 등판 이후 휴식일 수
    'api_break_z_with_gravity',  # 중력 포함 투구 낙폭 (낙차)
    'api_break_x_arm',  # 투수 기준 좌우 변화량
    'p_throws_L',  # 투수가 왼손잡이인지 여부 (One-hot)
    'p_throws_R',  # 투수가 오른손잡이인지 여부 (One-hot)
    'game_type_R',  # 경기 타입이 정규시즌(R)인지 여부 (정규 메타정보)
    'n_thruorder_pitcher',  # 해당 투수가 타자 라인업을 몇 번째 도는 중인지
    'if_fielding_alignment_Standard',  # 내야 수비 스탠다드 여부
    'if_fielding_alignment_Strategic',  # 내야 수비 전략적 배치 여부
    'of_fielding_alignment_Standard',  # 외야 수비 스탠다드 여부
    'of_fielding_alignment_Strategic'  # 외야 수비 전략적 배치 여부
]

swing_features = [
    'plate_x',  # 공이 홈플레이트 기준 좌우 어디를 통과했는지
    'plate_z',  # 공이 홈플레이트 기준 어느 높이를 통과했는지
    'balls',  # 현재 볼 카운트
    'strikes',  # 현재 스트라이크 카운트
    'outs_when_up',  # 타석 시점 아웃 카운트
    'bat_score_diff',  # 타석 시점 점수차 (타자 팀 기준)
    'api_break_x_batter_in',  # 타자 기준으로 몸쪽으로 휘는 정도
    'age_bat',  # 타자 나이
    'batter_days_since_prev_game',  # 타자의 마지막 출전 이후 휴식일 수
    'stand_L',  # 타자가 왼손잡이인지 여부 (One-hot)
    'stand_R',  # 타자가 오른손잡이인지 여부 (One-hot)
    'at_bat_number',  # 이 경기에서의 타석 번호
    'n_priorpa_thisgame_player_at_bat',  # 이 경기에서의 타자의 이전 타석 수
    'pitch_type',  # 투구 타입 코드 (ex. 'FF' 등)
    'zone',  # 스트라이크 존 번호 (1~14)
    'type',  # 결과 타입 (B: 볼, S: 스트라이크, X: 인플레이)
    'pitch_name',  # 구질 명칭 (ex. 4-Seam Fastball)
    'sz_top',  # 타자 기준 스트라이크 존 상단
    'sz_bot'   # 타자 기준 스트라이크 존 하단
]
'''
taf_pitch_cols = [
    'spin_efficiency_rolling_avg_5', 'spin_efficiency_lag_1', 'spin_efficiency_diff_1',
    'speed_gap_rolling_avg_5', 'speed_gap_lag_1', 'speed_gap_diff_1',
    'release_pos_angle_rolling_avg_5', 'release_pos_angle_lag_1', 'release_pos_angle_diff_1',
    'init_velocity_vector_rolling_avg_5', 'init_velocity_vector_lag_1', 'init_velocity_vector_diff_1',
    'pitch_movement_vector_rolling_avg_5', 'pitch_movement_vector_lag_1', 'pitch_movement_vector_diff_1',
    'speed_per_extension_rolling_avg_5', 'speed_per_extension_lag_1', 'speed_per_extension_diff_1',
    'release_mechanics_profile_rolling_avg_5', 'release_mechanics_profile_lag_1', 'release_mechanics_profile_diff_1',
    'vertical_spin_effect_rolling_avg_5', 'vertical_spin_effect_lag_1', 'vertical_spin_effect_diff_1',
    'horizontal_spin_effect_rolling_avg_5', 'horizontal_spin_effect_lag_1', 'horizontal_spin_effect_diff_1'
]
taf_swing_cols = [
    'plate_distance_rolling_avg_5', 'plate_distance_lag_1', 'plate_distance_diff_1'
]
'''

# pitch/swing 구분 키워드 정의 (기준 키워드)
pitch_keywords = [
    'spin_efficiency', 'speed_gap', 'release_pos_angle',
    'init_velocity_vector', 'pitch_movement_vector',
    'speed_per_extension', 'release_mechanics_profile',
    'vertical_spin_effect', 'horizontal_spin_effect'
]
swing_keywords = ['plate_distance']

# selected_taf_cols를 기준으로 분류
taf_pitch_cols = [col for col in selected_taf_cols if any(key in col for key in pitch_keywords)]
taf_swing_cols = [col for col in selected_taf_cols if any(key in col for key in swing_keywords)]

# pitch/swing feature 확장
pitch_features += taf_pitch_cols
swing_features += taf_swing_cols

# 확인
print(f"📌 pitch_features 총 개수: {len(pitch_features)}")
print(f"📌 swing_features 총 개수: {len(swing_features)}")

print("\n🎯 추가된 TAF pitch features:")
print(taf_pitch_cols)

print("\n🎯 추가된 TAF swing features:")
print(taf_swing_cols)

# ----------------------------- 6) Prediction
pred_rows = []  # 전체 매치 예측 누적용

# (date_str, match_id) → label 빠른 조회 맵
label_map = (
    y[['date_str', 'match_id', 'label']]
      .drop_duplicates(['date_str', 'match_id'])
      .set_index(['date_str', 'match_id'])['label']
      .to_dict()
)
label_map

num_matches (매치 수) :  1163
mean_cols_topbot len : 80
max_cols_topbot len : 8
mode_cols_topbot len : 16
📌 pitch_features 총 개수: 33
📌 swing_features 총 개수: 19

🎯 추가된 TAF pitch features:
['spin_efficiency_rolling_avg_5', 'speed_gap_diff_1', 'pitch_movement_vector_rolling_avg_5', 'vertical_spin_effect_lag_1']

🎯 추가된 TAF swing features:
[]

{('240329', 'TOR@TB'): 1,
 ('240329', 'PIT@MIA'): 0,
 ('240329', 'MIL@NYM'): 0,
 ('240329', 'BOS@SEA'): 1,
 ('240329', 'ATL@PHI'): 0,
 ('240329', 'NYY@HOU'): 0,
 ('240329', 'STL@LAD'): 1,
 ('240329', 'CLE@OAK'): 0,
 ('240329', 'SF@SD'): 0,
 ('240329', 'COL@AZ'): 1,
 ('240330', 'STL@LAD'): 0,
 ('240330', 'WSH@CIN'): 0,
 ('240330', 'CLE@OAK'): 0,
 ('240330', 'PIT@MIA'): 0,
 ('240330', 'SF@SD'): 0,
 ('240330', 'NYY@HOU'): 0,
 ('240330', 'MIN@KC'): 0,
 ('240330', 'ATL@PHI'): 0,
 ('240330', 'BOS@SEA'): 1,
 ('240330', 'TOR@TB'): 1,
 ('240330', 'MIL@NYM'): 0,
 ('240330', 'CHC@TEX'): 1,
 ('240330', 'LAA@BAL'): 1,
 ('240330', 'DET@CWS'): 0,
 ('240330', 'COL@AZ'): 0,
 ('240331', 'CLE@OAK'): 1,
 ('240331', 'ATL@PHI'): 1,
 ('240331', 'WSH@CIN'): 1,
 ('240331', 'NYY@HOU'): 0,
 ('240331', 'SF@SD'): 1,
 ('240331', 'BOS@SEA'): 0,
 ('240331', 'CHC@TEX'): 0,
 ('240331', 'MIL@NYM'): 0,
 ('240331', 'MIN@KC'): 1,
 ('240331', 'PIT@MIA'): 0,
 ('240331', 'LAA@BAL'): 0,
 ('240331', 'TOR@TB'): 0,
 ('240331', 'DET@CWS'): 0,
 ('240331', 'STL@LAD'): 1,
 ('240331', 'COL@AZ'): 1,
 ('240401', 'SF@LAD'): 1,
 ('240401', 'KC@BAL'): 1,
 ('240401', 'NYY@AZ'): 0,
 ('240401', 'ATL@CWS'): 0,
 ('240401', 'STL@SD'): 0,
 ('240401', 'CLE@SEA'): 1,
 ('240401', 'CIN@PHI'): 0,
 ('240401', 'DET@NYM'): 0,
 ('240401', 'TEX@TB'): 0,
 ('240401', 'BOS@OAK'): 0,
 ('240401', 'TOR@HOU'): 1,
 ('240401', 'LAA@MIA'): 0,
 ('240401', 'COL@CHC'): 1,
 ('240401', 'PIT@WSH'): 0,
 ('240402', 'BOS@OAK'): 0,
 ('240402', 'CIN@PHI'): 1,
 ('240402', 'STL@SD'): 0,
 ('240402', 'ATL@CWS'): 1,
 ('240402', 'LAA@MIA'): 0,
 ('240402', 'TOR@HOU'): 0,
 ('240402', 'KC@BAL'): 0,
 ('240402', 'NYY@AZ'): 1,
 ('240402', 'TEX@TB'): 1,
 ('240402', 'SF@LAD'): 1,
 ('240402', 'COL@CHC'): 1,
 ('240402', 'CLE@SEA'): 0,
 ('240402', 'MIN@MIL'): 1,
 ('240403', 'STL@SD'): 1,
 ('240403', 'CIN@PHI'): 0,
 ('240403', 'SF@LAD'): 1,
 ('240403', 'COL@CHC'): 1,
 ('240403', 'CLE@SEA'): 0,
 ('240403', 'NYY@AZ'): 0,
 ('240403', 'TOR@HOU'): 1,
 ('240403', 'BOS@OAK'): 0,
 ('240403', 'MIN@MIL'): 0,
 ('240403', 'LAA@MIA'): 0,
 ('240403', 'PIT@WSH'): 1,
 ('240403', 'TEX@TB'): 0,
 ('240403', 'KC@BAL'): 1,
 ('240404', 'MIA@STL'): 1,
 ('240404', 'PIT@WSH'): 0,
 ('240404', 'CWS@KC'): 1,
 ('240404', 'CLE@MIN'): 0,
 ('240404', 'DET@NYM'): 0,
 ('240405', 'SD@SF'): 1,
 ('240405', 'BAL@PIT'): 0,
 ('240405', 'SEA@MIL'): 1,
 ('240405', 'LAD@CHC'): 1,
 ('240405', 'NYM@CIN'): 0,
 ('240405', 'TOR@NYY'): 0,
 ('240405', 'OAK@DET'): 1,
 ('240405', 'AZ@ATL'): 1,
 ('240405', 'HOU@TEX'): 1,
 ('240405', 'CWS@KC'): 1,
 ('240405', 'BOS@LAA'): 0,
 ('240405', 'PHI@WSH'): 0,
 ('240405', 'TB@COL'): 1,
 ('240406', 'AZ@ATL'): 1,
 ('240406', 'PHI@WSH'): 0,
 ('240406', 'MIA@STL'): 1,
 ('240406', 'CLE@MIN'): 0,
 ('240406', 'OAK@DET'): 0,
 ('240406', 'SD@SF'): 0,
 ('240406', 'BOS@LAA'): 1,
 ('240406', 'BAL@PIT'): 1,
 ('240406', 'TB@COL'): 0,
 ('240406', 'HOU@TEX'): 1,
 ('240406', 'SEA@MIL'): 0,
 ('240406', 'NYM@CIN'): 1,
 ('240406', 'LAD@CHC'): 0,
 ('240406', 'TOR@NYY'): 1,
 ('240406', 'CWS@KC'): 1,
 ('240407', 'CWS@KC'): 1,
 ('240407', 'OAK@DET'): 0,
 ('240407', 'MIA@STL'): 0,
 ('240407', 'BOS@LAA'): 0,
 ('240407', 'BAL@PIT'): 1,
 ('240407', 'SEA@MIL'): 1,
 ('240407', 'AZ@ATL'): 1,
 ('240407', 'TOR@NYY'): 1,
 ('240407', 'SD@SF'): 1,
 ('240407', 'HOU@TEX'): 0,
 ('240407', 'NYM@CIN'): 0,
 ('240407', 'TB@COL'): 0,
 ('240407', 'LAD@CHC'): 1,
 ('240407', 'PHI@WSH'): 1,
 ('240408', 'CWS@CLE'): 1,
 ('240408', 'MIA@NYY'): 1,
 ('240408', 'AZ@COL'): 1,
 ('240408', 'CHC@SD'): 1,
 ('240408', 'SEA@TOR'): 1,
 ('240408', 'WSH@SF'): 0,
 ('240408', 'DET@PIT'): 1,
 ('240408', 'PHI@STL'): 0,
 ('240408', 'MIL@CIN'): 1,
 ('240408', 'TB@LAA'): 1,
 ('240408', 'LAD@MIN'): 0,
 ('240408', 'HOU@TEX'): 0,
 ('240408', 'NYM@ATL'): 0,
 ('240409', 'SEA@TOR'): 1,
 ('240409', 'CHC@SD'): 0,
 ('240409', 'OAK@TEX'): 0,
 ('240409', 'NYM@ATL'): 1,
 ('240409', 'AZ@COL'): 0,
 ('240409', 'DET@PIT'): 0,
 ('240409', 'HOU@KC'): 1,
 ('240409', 'CWS@CLE'): 0,
 ('240409', 'WSH@SF'): 0,
 ('240409', 'PHI@STL'): 1,
 ('240409', 'TB@LAA'): 0,
 ('240409', 'MIA@NYY'): 1,
 ('240409', 'BAL@BOS'): 0,
 ('240409', 'LAD@MIN'): 0,
 ('240409', 'MIL@CIN'): 0,
 ('240410', 'CHC@SD'): 1,
 ('240410', 'HOU@KC'): 1,
 ('240410', 'AZ@COL'): 0,
 ('240410', 'OAK@TEX'): 1,
 ('240410', 'SEA@TOR'): 0,
 ('240410', 'WSH@SF'): 1,
 ('240410', 'MIL@CIN'): 0,
 ('240410', 'CWS@CLE'): 1,
 ('240410', 'TB@LAA'): 0,
 ('240410', 'MIA@NYY'): 0,
 ('240410', 'BAL@BOS'): 0,
 ('240410', 'LAD@MIN'): 1,
 ('240410', 'PHI@STL'): 0,
 ('240411', 'HOU@KC'): 1,
 ('240411', 'BAL@BOS'): 0,
 ('240411', 'NYM@ATL'): 0,
 ('240411', 'PIT@PHI'): 1,
 ('240411', 'OAK@TEX'): 0,
 ('240412', 'MIN@DET'): 1,
 ('240412', 'SF@TB'): 1,
 ('240412', 'PIT@PHI'): 0,
 ('240412', 'SD@LAD'): 0,
 ('240412', 'CIN@CWS'): 0,
 ('240412', 'LAA@BOS'): 0,
 ('240412', 'CHC@SEA'): 1,
 ('240412', 'MIL@BAL'): 0,
 ('240412', 'STL@AZ'): 0,
 ('240412', 'WSH@OAK'): 1,
 ('240412', 'KC@NYM'): 1,
 ('240412', 'COL@TOR'): 0,
 ('240412', 'TEX@HOU'): 0,
 ('240412', 'ATL@MIA'): 0,
 ('240413', 'CHC@SEA'): 0,
 ('240413', 'NYY@CLE'): 0,
 ('240413', 'COL@TOR'): 1,
 ('240413', 'LAA@BOS'): 1,
 ('240413', 'TEX@HOU'): 1,
 ('240413', 'MIN@DET'): 0,
 ('240413', 'WSH@OAK'): 0,
 ('240413', 'STL@AZ'): 1,
 ('240413', 'CIN@CWS'): 0,
 ('240413', 'SF@TB'): 0,
 ('240413', 'MIL@BAL'): 0,
 ('240413', 'SD@LAD'): 1,
 ('240413', 'KC@NYM'): 0,
 ('240413', 'ATL@MIA'): 1,
 ('240413', 'PIT@PHI'): 1,
 ('240414', 'MIN@DET'): 1,
 ('240414', 'MIL@BAL'): 1,
 ('240414', 'STL@AZ'): 1,
 ('240414', 'KC@NYM'): 1,
 ('240414', 'CHC@SEA'): 0,
 ('240414', 'ATL@MIA'): 0,
 ('240414', 'PIT@PHI'): 0,
 ('240414', 'NYY@CLE'): 1,
 ('240414', 'CIN@CWS'): 0,
 ('240414', 'WSH@OAK'): 1,
 ('240414', 'SF@TB'): 1,
 ('240414', 'COL@TOR'): 1,
 ('240414', 'TEX@HOU'): 1,
 ('240414', 'SD@LAD'): 0,
 ('240414', 'LAA@BOS'): 1,
 ('240415', 'STL@OAK'): 0,
 ('240415', 'CIN@SEA'): 1,
 ('240415', 'LAA@TB'): 0,
 ('240415', 'KC@CWS'): 0,
 ('240415', 'CLE@BOS'): 0,
 ('240415', 'MIN@BAL'): 1,
 ('240415', 'ATL@HOU'): 0,
 ('240415', 'PIT@NYM'): 1,
 ('240415', 'WSH@LAD'): 0,
 ('240415', 'CHC@AZ'): 0,
 ('240415', 'NYY@TOR'): 1,
 ('240415', 'SF@MIA'): 0,
 ('240415', 'COL@PHI'): 1,
 ('240415', 'TEX@DET'): 0,
 ('240415', 'SD@MIL'): 0,
 ('240416', 'MIN@BAL'): 1,
 ('240416', 'CLE@BOS'): 0,
 ('240416', 'SD@MIL'): 0,
 ('240416', 'COL@PHI'): 1,
 ('240416', 'TEX@DET'): 1,
 ('240416', 'CIN@SEA'): 1,
 ('240416', 'STL@OAK'): 0,
 ('240416', 'SF@MIA'): 1,
 ('240416', 'WSH@LAD'): 1,
 ('240416', 'CHC@AZ'): 1,
 ('240416', 'NYY@TOR'): 1,
 ('240416', 'ATL@HOU'): 0,
 ('240416', 'LAA@TB'): 1,
 ('240416', 'PIT@NYM'): 1,
 ('240417', 'KC@CWS'): 1,
 ('240417', 'PIT@NYM'): 1,
 ('240417', 'CHC@AZ'): 0,
 ('240417', 'CLE@BOS'): 1,
 ('240417', 'SD@MIL'): 1,
 ('240417', 'MIN@BAL'): 1,
 ('240417', 'WSH@LAD'): 0,
 ('240417', 'COL@PHI'): 1,
 ('240417', 'SF@MIA'): 0,
 ('240417', 'STL@OAK'): 1,
 ('240417', 'LAA@TB'): 0,
 ('240417', 'ATL@HOU'): 0,
 ('240417', 'NYY@TOR'): 0,
 ('240417', 'CIN@SEA'): 1,
 ('240417', 'TEX@DET'): 0,
 ('240418', 'AZ@SF'): 1,
 ('240418', 'CLE@BOS'): 0,
 ('240418', 'LAA@TB'): 1,
 ('240418', 'TEX@DET'): 0,
 ('240419', 'OAK@CLE'): 1,
 ('240419', 'TB@NYY'): 1,
 ('240419', 'NYM@LAD'): 0,
 ('240419', 'DET@MIN'): 0,
 ('240419', 'BAL@KC'): 1,
 ('240419', 'TOR@SD'): 0,
 ('240419', 'CWS@PHI'): 1,
 ('240419', 'HOU@WSH'): 0,
 ('240419', 'AZ@SF'): 0,
 ('240419', 'BOS@PIT'): 0,
 ('240419', 'LAA@CIN'): 1,
 ('240419', 'TEX@ATL'): 1,
 ('240419', 'MIA@CHC'): 1,
 ('240419', 'MIL@STL'): 0,
 ('240420', 'MIA@CHC'): 0,
 ('240420', 'LAA@CIN'): 1,
 ('240420', 'MIL@STL'): 0,
 ('240420', 'BAL@KC'): 0,
 ('240420', 'HOU@WSH'): 1,
 ('240420', 'TOR@SD'): 0,
 ('240420', 'AZ@SF'): 1,
 ('240420', 'SEA@COL'): 0,
 ('240420', 'NYM@LAD'): 0,
 ('240420', 'TB@NYY'): 0,
 ('240420', 'CWS@PHI'): 1,
 ('240420', 'OAK@CLE'): 1,
 ('240420', 'BOS@PIT'): 0,
 ('240420', 'DET@MIN'): 1,
 ('240420', 'TEX@ATL'): 1,
 ('240421', 'SEA@COL'): 1,
 ('240421', 'LAA@CIN'): 1,
 ('240421', 'HOU@WSH'): 1,
 ('240421', 'NYM@LAD'): 1,
 ('240421', 'DET@MIN'): 0,
 ('240421', 'OAK@CLE'): 1,
 ('240421', 'TB@NYY'): 1,
 ('240421', 'CWS@PHI'): 1,
 ('240421', 'TEX@ATL'): 0,
 ('240421', 'TOR@SD'): 1,
 ('240421', 'AZ@SF'): 0,
 ('240421', 'MIL@STL'): 0,
 ('240421', 'BOS@PIT'): 0,
 ('240421', 'BAL@KC'): 0,
 ('240421', 'MIA@CHC'): 0,
 ('240422', 'AZ@STL'): 1,
 ('240422', 'PHI@CIN'): 0,
 ('240422', 'BAL@LAA'): 0,
 ('240422', 'CWS@MIN'): 1,
 ('240422', 'TOR@KC'): 0,
 ('240422', 'SD@COL'): 0,
 ('240422', 'NYM@SF'): 1,
 ('240422', 'OAK@NYY'): 0,
 ('240422', 'MIL@PIT'): 1,
 ('240422', 'DET@TB'): 0,
 ('240422', 'MIA@ATL'): 1,
 ('240423', 'CWS@MIN'): 1,
 ('240423', 'LAD@WSH'): 0,
 ('240423', 'BOS@CLE'): 1,
 ('240423', 'TOR@KC'): 1,
 ('240423', 'MIA@ATL'): 1,
 ('240423', 'SEA@TEX'): 0,
 ('240423', 'PHI@CIN'): 1,
 ('240423', 'HOU@CHC'): 1,
 ('240423', 'MIL@PIT'): 1,
 ('240423', 'SD@COL'): 1,
 ('240423', 'NYM@SF'): 1,
 ('240423', 'AZ@STL'): 0,
 ('240423', 'DET@TB'): 0,
 ('240423', 'OAK@NYY'): 1,
 ('240423', 'BAL@LAA'): 1,
 ('240424', 'LAD@WSH'): 0,
 ('240424', 'OAK@NYY'): 1,
 ('240424', 'PHI@CIN'): 1,
 ('240424', 'MIL@PIT'): 0,
 ('240424', 'CWS@MIN'): 1,
 ('240424', 'SD@COL'): 0,
 ('240424', 'BOS@CLE'): 0,
 ('240424', 'SEA@TEX'): 1,
 ('240424', 'MIA@ATL'): 1,
 ('240424', 'NYM@SF'): 0,
 ('240424', 'AZ@STL'): 1,
 ('240424', 'HOU@CHC'): 1,
 ('240424', 'DET@TB'): 1,
 ('240424', 'BAL@LAA'): 0,
 ('240424', 'TOR@KC'): 1,
 ('240425', 'LAD@WSH'): 0,
 ('240425', 'TOR@KC'): 1,
 ('240425', 'PHI@CIN'): 0,
 ('240425', 'OAK@NYY'): 0,
 ('240425', 'HOU@CHC'): 1,
 ('240425', 'BOS@CLE'): 1,
 ('240425', 'CWS@MIN'): 1,
 ('240425', 'SEA@TEX'): 0,
 ('240425', 'SD@COL'): 1,
 ('240425', 'MIL@PIT'): 0,
 ('240426', 'PHI@SD'): 0,
 ('240426', 'CLE@ATL'): 1,
 ('240426', 'CIN@TEX'): 1,
 ('240426', 'KC@DET'): 0,
 ('240426', 'CHC@BOS'): 0,
 ('240426', 'OAK@BAL'): 0,
 ('240426', 'MIN@LAA'): 0,
 ('240426', 'LAD@TOR'): 0,
 ('240426', 'PIT@SF'): 1,
 ('240426', 'WSH@MIA'): 0,
 ('240426', 'TB@CWS'): 1,
 ('240426', 'NYY@MIL'): 1,
 ('240426', 'STL@NYM'): 0,
 ('240426', 'AZ@SEA'): 1,
 ('240427', 'TB@CWS'): 1,
 ('240427', 'CLE@ATL'): 0,
 ('240427', 'LAD@TOR'): 0,
 ('240427', 'PHI@SD'): 0,
 ('240427', 'CHC@BOS'): 1,
 ('240427', 'HOU@COL'): 0,
 ('240427', 'NYY@MIL'): 0,
 ('240427', 'CIN@TEX'): 0,
 ('240427', 'PIT@SF'): 0,
 ('240427', 'MIN@LAA'): 0,
 ('240427', 'AZ@SEA'): 1,
 ('240427', 'STL@NYM'): 0,
 ('240427', 'KC@DET'): 1,
 ('240427', 'WSH@MIA'): 0,
 ('240427', 'OAK@BAL'): 1,
 ('240428', 'CHC@BOS'): 1,
 ('240428', 'AZ@SEA'): 0,
 ('240428', 'STL@NYM'): 1,
 ('240428', 'CIN@TEX'): 1,
 ('240428', 'LAD@TOR'): 1,
 ('240428', 'PHI@SD'): 0,
 ('240428', 'MIN@LAA'): 0,
 ('240428', 'OAK@BAL'): 0,
 ('240428', 'PIT@SF'): 1,
 ('240428', 'TB@CWS'): 1,
 ('240428', 'KC@DET'): 1,
 ('240428', 'WSH@MIA'): 0,
 ('240428', 'HOU@COL'): 0,
 ('240428', 'CLE@ATL'): 1,
 ('240428', 'NYY@MIL'): 0,
 ('240429', 'PHI@LAA'): 1,
 ('240429', 'ATL@SEA'): 1,
 ('240429', 'CHC@NYM'): 0,
 ('240429', 'TB@MIL'): 0,
 ('240429', 'NYY@BAL'): 1,
 ('240429', 'LAD@AZ'): 0,
 ('240429', 'WSH@MIA'): 0,
 ('240429', 'MIN@CWS'): 0,
 ('240429', 'PIT@OAK'): 1,
 ('240429', 'KC@TOR'): 1,
 ('240429', 'CIN@SD'): 0,
 ('240430', 'SF@BOS'): 1,
 ('240430', 'ATL@SEA'): 1,
 ('240430', 'MIN@CWS'): 0,
 ('240430', 'KC@TOR'): 0,
 ('240430', 'CIN@SD'): 1,
 ('240430', 'PIT@OAK'): 1,
 ('240430', 'COL@MIA'): 1,
 ('240430', 'CHC@NYM'): 1,
 ('240430', 'STL@DET'): 0,
 ('240430', 'CLE@HOU'): 1,
 ('240430', 'PHI@LAA'): 0,
 ('240430', 'WSH@TEX'): 1,
 ('240430', 'LAD@AZ'): 1,
 ('240430', 'NYY@BAL'): 1,
 ('240430', 'TB@MIL'): 1,
 ('240501', 'ATL@SEA'): 0,
 ('240501', 'CLE@HOU'): 0,
 ('240501', 'PIT@OAK'): 1,
 ('240501', 'LAD@AZ'): 0,
 ('240501', 'NYY@BAL'): 0,
 ('240501', 'CHC@NYM'): 0,
 ('240501', 'COL@MIA'): 1,
 ('240501', 'SF@BOS'): 1,
 ('240501', 'MIN@CWS'): 0,
 ('240501', 'KC@TOR'): 0,
 ('240501', 'CIN@SD'): 1,
 ('240501', 'WSH@TEX'): 0,
 ('240501', 'STL@DET'): 1,
 ('240501', 'TB@MIL'): 1,
 ('240501', 'PHI@LAA'): 0,
 ('240502', 'CLE@HOU'): 1,
 ('240502', 'SF@BOS'): 0,
 ('240502', 'NYY@BAL'): 1,
 ('240502', 'WSH@TEX'): 1,
 ('240502', 'CHC@NYM'): 1,
 ('240502', 'COL@MIA'): 1,
 ('240503', 'ATL@LAD'): 1,
 ('240503', 'TOR@WSH'): 1,
 ('240503', 'BAL@CIN'): 0,
 ('240503', 'TEX@KC'): 1,
 ('240503', 'DET@NYY'): 1,
 ('240503', 'MIL@CHC'): 0,
 ('240503', 'LAA@CLE'): 0,
 ('240503', 'SF@PHI'): 1,
 ('240503', 'COL@PIT'): 0,
 ('240503', 'SD@AZ'): 0,
 ('240503', 'CWS@STL'): 1,
 ('240503', 'NYM@TB'): 1,
 ('240503', 'SEA@HOU'): 1,
 ('240503', 'BOS@MIN'): 1,
 ('240503', 'MIA@OAK'): 1,
 ('240504', 'LAA@CLE'): 1,
 ('240504', 'NYM@TB'): 1,
 ('240504', 'SEA@HOU'): 0,
 ('240504', 'MIA@OAK'): 1,
 ('240504', 'BAL@CIN'): 0,
 ('240504', 'CWS@STL'): 0,
 ('240504', 'TEX@KC'): 0,
 ('240504', 'MIL@CHC'): 1,
 ('240504', 'DET@NYY'): 1,
 ('240504', 'TOR@WSH'): 0,
 ('240504', 'SF@PHI'): 1,
 ('240504', 'ATL@LAD'): 1,
 ('240504', 'COL@PIT'): 1,
 ('240504', 'SD@AZ'): 0,
 ('240504', 'BOS@MIN'): 1,
 ('240505', 'MIL@CHC'): 1,
 ('240505', 'SEA@HOU'): 0,
 ('240505', 'DET@NYY'): 1,
 ('240505', 'TOR@WSH'): 1,
 ('240505', 'TEX@KC'): 0,
 ('240505', 'ATL@LAD'): 1,
 ('240505', 'CWS@STL'): 0,
 ('240505', 'NYM@TB'): 1,
 ('240505', 'BOS@MIN'): 0,
 ('240505', 'LAA@CLE'): 1,
 ('240505', 'COL@PIT'): 1,
 ('240505', 'BAL@CIN'): 0,
 ('240505', 'MIA@OAK'): 0,
 ('240505', 'SF@PHI'): 1,
 ('240505', 'SD@AZ'): 1,
 ('240506', 'SEA@MIN'): 1,
 ('240506', 'SF@PHI'): 1,
 ('240506', 'MIL@KC'): 1,
 ('240506', 'LAA@PIT'): 1,
 ('240506', 'TEX@OAK'): 0,
 ('240506', 'NYM@STL'): 0,
 ('240506', 'CWS@TB'): 1,
 ('240506', 'SD@CHC'): 0,
 ('240506', 'MIA@LAD'): 1,
 ('240506', 'DET@CLE'): 1,
 ('240507', 'MIA@LAD'): 1,
 ('240507', 'CWS@TB'): 1,
 ('240507', 'BOS@ATL'): 1,
 ('240507', 'SEA@MIN'): 0,
 ('240507', 'NYM@STL'): 0,
 ('240507', 'SF@COL'): 0,
 ('240507', 'MIL@KC'): 0,
 ('240507', 'TEX@OAK'): 0,
 ('240507', 'LAA@PIT'): 0,
 ('240507', 'HOU@NYY'): 1,
 ('240507', 'DET@CLE'): 0,
 ('240507', 'AZ@CIN'): 0,
 ('240507', 'SD@CHC'): 1,
 ('240507', 'BAL@WSH'): 1,
 ('240507', 'TOR@PHI'): 1,
 ('240508', 'MIA@LAD'): 1,
 ('240508', 'CWS@TB'): 0,
 ('240508', 'SEA@MIN'): 1,
 ('240508', 'TEX@OAK'): 0,
 ('240508', 'AZ@CIN'): 0,
 ('240508', 'BOS@ATL'): 1,
 ('240508', 'SD@CHC'): 0,
 ('240508', 'SF@COL'): 0,
 ('240508', 'DET@CLE'): 1,
 ('240508', 'TOR@PHI'): 0,
 ('240508', 'LAA@PIT'): 0,
 ('240508', 'MIL@KC'): 1,
 ('240508', 'HOU@NYY'): 1,
 ('240508', 'BAL@WSH'): 0,
 ('240509', 'SEA@MIN'): 1,
 ('240509', 'AZ@CIN'): 0,
 ('240509', 'KC@LAA'): 0,
 ('240509', 'SF@COL'): 1,
 ('240509', 'STL@MIL'): 1,
 ('240509', 'HOU@NYY'): 0,
 ('240509', 'CLE@CWS'): 1,
 ('240510', 'HOU@DET'): 0,
 ('240510', 'CHC@PIT'): 0,
 ('240510', 'TEX@COL'): 1,
 ('240510', 'LAD@SD'): 1,
 ('240510', 'KC@LAA'): 0,
 ('240510', 'CLE@CWS'): 1,
 ('240510', 'AZ@BAL'): 1,
 ('240510', 'ATL@NYM'): 0,
 ('240510', 'NYY@TB'): 0,
 ('240510', 'PHI@MIA'): 0,
 ('240510', 'STL@MIL'): 1,
 ('240510', 'OAK@SEA'): 1,
 ('240510', 'CIN@SF'): 0,
 ('240510', 'MIN@TOR'): 0,
 ('240510', 'WSH@BOS'): 0,
 ('240511', 'STL@MIL'): 1,
 ('240511', 'PHI@MIA'): 0,
 ('240511', 'CHC@PIT'): 1,
 ('240511', 'OAK@SEA'): 0,
 ('240511', 'NYY@TB'): 1,
 ('240511', 'MIN@TOR'): 1,
 ('240511', 'CLE@CWS'): 1,
 ('240511', 'KC@LAA'): 1,
 ('240511', 'WSH@BOS'): 1,
 ('240511', 'ATL@NYM'): 0,
 ('240511', 'AZ@BAL'): 1,
 ('240511', 'HOU@DET'): 1,
 ('240511', 'LAD@SD'): 0,
 ('240511', 'CIN@SF'): 1,
 ('240511', 'TEX@COL'): 1,
 ('240512', 'CHC@PIT'): 0,
 ('240512', 'WSH@BOS'): 1,
 ('240512', 'STL@MIL'): 0,
 ('240512', 'HOU@DET'): 0,
 ('240512', 'CIN@SF'): 1,
 ('240512', 'PHI@MIA'): 1,
 ('240512', 'NYY@TB'): 0,
 ('240512', 'LAD@SD'): 1,
 ('240512', 'CLE@CWS'): 0,
 ('240512', 'ATL@NYM'): 1,
 ('240512', 'KC@LAA'): 0,
 ('240512', 'TEX@COL'): 1,
 ('240512', 'MIN@TOR'): 0,
 ('240512', 'OAK@SEA'): 1,
 ('240512', 'AZ@BAL'): 0,
 ('240513', 'TOR@BAL'): 0,
 ('240513', 'PIT@MIL'): 0,
 ('240513', 'LAD@SF'): 0,
 ('240513', 'OAK@HOU'): 1,
 ('240513', 'COL@SD'): 0,
 ('240513', 'KC@SEA'): 1,
 ('240513', 'TB@BOS'): 0,
 ('240513', 'CLE@TEX'): 0,
 ('240513', 'PHI@NYM'): 0,
 ('240513', 'MIA@DET'): 1,
 ('240513', 'CIN@AZ'): 1,
 ('240513', 'STL@LAA'): 0,
 ('240513', 'CHC@ATL'): 1,
 ('240514', 'PHI@NYM'): 0,
 ('240514', 'WSH@CWS'): 1,
 ('240514', 'CLE@TEX'): 0,
 ('240514', 'KC@SEA'): 0,
 ('240514', 'CHC@ATL'): 1,
 ('240514', 'COL@SD'): 0,
 ('240514', 'PIT@MIL'): 1,
 ('240514', 'MIA@DET'): 0,
 ('240514', 'STL@LAA'): 0,
 ('240514', 'TB@BOS'): 1,
 ('240514', 'NYY@MIN'): 0,
 ('240514', 'LAD@SF'): 0,
 ('240514', 'CIN@AZ'): 0,
 ('240514', 'OAK@HOU'): 1,
 ('240515', 'MIA@DET'): 0,
 ('240515', 'CHC@ATL'): 0,
 ('240515', 'CLE@TEX'): 1,
 ('240515', 'LAD@SF'): 1,
 ('240515', 'KC@SEA'): 1,
 ('240515', 'PIT@MIL'): 1,
 ('240515', 'COL@SD'): 0,
 ('240515', 'NYY@MIN'): 0,
 ('240515', 'NYM@PHI'): 1,
 ('240515', 'WSH@CWS'): 1,
 ('240515', 'STL@LAA'): 1,
 ('240515', 'OAK@HOU'): 1,
 ('240515', 'TB@BOS'): 0,
 ('240515', 'CIN@AZ'): 1,
 ('240515', 'TOR@BAL'): 1,
 ('240516', 'NYM@PHI'): 0,
 ('240516', 'TB@BOS'): 0,
 ('240516', 'NYY@MIN'): 0,
 ('240516', 'PIT@CHC'): 0,
 ('240516', 'OAK@HOU'): 1,
 ('240516', 'CIN@LAD'): 0,
 ('240517', 'LAA@TEX'): 0,
 ('240517', 'PIT@CHC'): 0,
 ('240517', 'DET@AZ'): 0,
 ('240517', 'MIN@CLE'): 1,
 ('240517', 'COL@SF'): 1,
 ('240517', 'CWS@NYY'): 1,
 ('240517', 'SEA@BAL'): 1,
 ('240517', 'TB@TOR'): 0,
 ('240517', 'WSH@PHI'): 1,
 ('240517', 'BOS@STL'): 1,
 ('240517', 'NYM@MIA'): 1,
 ('240517', 'MIL@HOU'): 1,
 ('240517', 'CIN@LAD'): 1,
 ('240517', 'OAK@KC'): 1,
 ('240517', 'SD@ATL'): 0,
 ('240518', 'CIN@LAD'): 1,
 ('240518', 'WSH@PHI'): 1,
 ('240518', 'MIL@HOU'): 0,
 ('240518', 'BOS@STL'): 1,
 ('240518', 'SEA@BAL'): 0,
 ('240518', 'OAK@KC'): 1,
 ('240518', 'DET@AZ'): 0,
 ('240518', 'MIN@CLE'): 1,
 ('240518', 'NYM@MIA'): 1,
 ('240518', 'LAA@TEX'): 1,
 ('240518', 'TB@TOR'): 0,
 ('240518', 'CWS@NYY'): 1,
 ('240518', 'PIT@CHC'): 1,
 ('240518', 'COL@SF'): 1,
 ('240519', 'TB@TOR'): 1,
 ('240519', 'MIL@HOU'): 1,
 ('240519', 'WSH@PHI'): 1,
 ('240519', 'SD@ATL'): 0,
 ('240519', 'SEA@BAL'): 1,
 ('240519', 'DET@AZ'): 1,
 ('240519', 'CIN@LAD'): 1,
 ('240519', 'PIT@CHC'): 0,
 ('240519', 'BOS@STL'): 0,
 ('240519', 'LAA@TEX'): 0,
 ('240519', 'OAK@KC'): 1,
 ('240519', 'COL@SF'): 1,
 ('240519', 'NYM@MIA'): 0,
 ('240519', 'CWS@NYY'): 1,
 ('240519', 'MIN@CLE'): 1,
 ('240520', 'MIL@MIA'): 1,
 ('240520', 'BOS@TB'): 0,
 ('240520', 'MIN@WSH'): 1,
 ('240520', 'DET@KC'): 1,
 ('240520', 'AZ@LAD'): 1,
 ('240520', 'BAL@STL'): 1,
 ('240520', 'SD@ATL'): 1,
 ('240520', 'LAA@HOU'): 0,
 ('240520', 'CWS@TOR'): 1,
 ('240520', 'SEA@NYY'): 0,
 ('240520', 'NYM@CLE'): 1,
 ('240521', 'SEA@NYY'): 0,
 ('240521', 'MIL@MIA'): 0,
 ('240521', 'SD@CIN'): 1,
 ('240521', 'ATL@CHC'): 1,
 ('240521', 'CWS@TOR'): 0,
 ('240521', 'NYM@CLE'): 1,
 ('240521', 'COL@OAK'): 1,
 ('240521', 'SF@PIT'): 1,
 ('240521', 'TEX@PHI'): 1,
 ('240521', 'LAA@HOU'): 1,
 ('240521', 'BAL@STL'): 1,
 ('240521', 'AZ@LAD'): 0,
 ('240521', 'DET@KC'): 1,
 ('240521', 'MIN@WSH'): 0,
 ('240521', 'BOS@TB'): 0,
 ('240522', 'SD@CIN'): 0,
 ('240522', 'MIN@WSH'): 0,
 ('240522', 'LAA@HOU'): 0,
 ('240522', 'DET@KC'): 1,
 ('240522', 'MIL@MIA'): 1,
 ('240522', 'COL@OAK'): 0,
 ('240522', 'AZ@LAD'): 0,
 ('240522', 'SF@PIT'): 0,
 ('240522', 'BOS@TB'): 0,
 ('240522', 'CWS@TOR'): 1,
 ('240522', 'TEX@PHI'): 1,
 ('240522', 'SEA@NYY'): 1,
 ('240522', 'ATL@CHC'): 0,
 ('240522', 'BAL@STL'): 1,
 ('240522', 'NYM@CLE'): 1,
 ('240523', 'COL@OAK'): 1,
 ('240523', 'TOR@DET'): 0,
 ('240523', 'SD@CIN'): 0,
 ('240523', 'SF@PIT'): 0,
 ('240523', 'SEA@NYY'): 1,
 ('240523', 'TEX@PHI'): 1,
 ('240523', 'ATL@CHC'): 0,
 ('240523', 'BAL@CWS'): 0,
 ('240524', 'MIA@AZ'): 0,
 ('240524', 'CLE@LAA'): 0,
 ('240524', 'SF@NYM'): 0,
 ('240524', 'HOU@OAK'): 0,
 ('240524', 'MIL@BOS'): 0,
 ('240524', 'ATL@PIT'): 1,
 ('240524', 'PHI@COL'): 1,
 ('240524', 'LAD@CIN'): 1,
 ('240524', 'NYY@SD'): 0,
 ('240524', 'TOR@DET'): 1,
 ('240524', 'BAL@CWS'): 0,
 ('240524', 'KC@TB'): 0,
 ('240524', 'TEX@MIN'): 1,
 ('240524', 'SEA@WSH'): 1,
 ('240525', 'PHI@COL'): 0,
 ('240525', 'KC@TB'): 0,
 ('240525', 'CLE@LAA'): 0,
 ('240525', 'MIA@AZ'): 1,
 ('240525', 'TOR@DET'): 1,
 ('240525', 'ATL@PIT'): 1,
 ('240525', 'MIL@BOS'): 0,
 ('240525', 'SEA@WSH'): 1,

In [131]:
X["date_int"] = X["date_str"].apply(to_int_date)
y["date_int"] = y["date_str"].apply(to_int_date)

all_matches = []  # 루프에서 매치 정보 모을 리스트
split_summaries = []   # 매치별 카운트/경계만 요약 저장

df_detail_train  = []   # 행별 상세 기록 누적 (여러 stage 합쳐서)
df_detail_valid  = []   # 행별 상세 기록 누적 (여러 stage 합쳐서)
df_detail_test  = []   # 행별 상세 기록 누적 (여러 stage 합쳐서)

with open("pred_match_dict.jsonl", "r", encoding="utf-8") as f:
    lines = [ln for ln in f if ln.strip()]
     
# 반복할 매치 개수

repeat_limit = None
'''
repeat_limit = 3
'''
print("repeat_limit (정한 매치 수) : ", repeat_limit)

# 전체 매치 수와 비교해서 반복 개수 결정
repeat_count = num_matches if repeat_limit is None else min(repeat_limit, num_matches)
print("num_matches:", num_matches, "| repeat_count:", repeat_count)


for i in range(repeat_count):
    '''
    1) pred_match_dict.jsonl 정보 변수에 저장
    2) X 중 해당 매치의 train, valid, test, new 로 필요한 줄들을 복사
    3) train
    4) valid, test 평가
    5) new 합성
    6) new 를 model 에 넣어 결과
    '''
    
    line = lines[i].strip()
    plan = json.loads(line)

    # ----------------------------- 1) pred_match_dict.jsonl 정보 변수에 저장
    pred_date            = plan["pred_date"]
    match_id             = plan["match_id"]
    window               = int(plan["window"])
    away_team            = plan["away_team"]
    home_team            = plan["home_team"]
    train_available_date = plan["train_available_date"]

    away_games           = plan["away_games"]  # [{"order":1,"game_pk":..., "date_str":..., "match_id":...}, ...]
    home_games           = plan["home_games"]
    
    
    # ----------------------------- 2) X 중 해당 매치의 train, valid, test, new 로 필요한 줄들을 복사
    # 2-1) new
    # away / home game_pk 뽑기
    away_ids = [g["game_pk"] for g in plan["away_games"]]
    home_ids = [g["game_pk"] for g in plan["home_games"]]

    # X, y 에서 해당 줄 추출
    X_new_away = X[X["game_pk"].isin(away_ids)].copy()
    X_new_home = X[X["game_pk"].isin(home_ids)].copy()
    
    y_new_away = y[y["game_pk"].isin(away_ids)].copy()
    y_new_home = y[y["game_pk"].isin(home_ids)].copy()


    # 2-2) 과거 데이터(= train_available_date 이전까지)
    train_available_int = to_int_date(train_available_date)

    # X, y cutoff 이전 데이터만 추출
    past_mask_X = X["date_int"] <= train_available_int
    X_past_all = (
        X.loc[past_mask_X]
        .copy()
        .sort_values(["date_int", "match_id", "game_pk"])
    )
    
    past_mask_y = y["date_int"] <= train_available_int
    y_past_all = (
        y.loc[past_mask_y]
        .copy()
        .sort_values(["date_int", "match_id", "game_pk"])
    )


    # 2-3) 8:1:1 근사치 분할 + 나머지는 test에 몰아주기
    nX_total = len(X_past_all)
    nX_tr, nX_va, nX_te = split_counts_by_ratio(nX_total, ratios=(0.8, 0.1, 0.1))

    X_train, X_valid, X_test = (
        X_past_all.iloc[:nX_tr],
        X_past_all.iloc[nX_tr:nX_tr+nX_va],
        X_past_all.iloc[nX_tr+nX_va:]
    )
    
    ny_total = len(y_past_all)
    ny_tr, ny_va, ny_te = split_counts_by_ratio(ny_total, ratios=(0.8, 0.1, 0.1))

    y_train, y_valid, y_test = (
        y_past_all.iloc[:ny_tr],
        y_past_all.iloc[ny_tr:ny_tr+ny_va],
        y_past_all.iloc[ny_tr+ny_va:]
    )
    
    '''
    X_train, X_valid, X_test
    y_train, y_valid, y_test
    '''
    
    
    # ----------------------------- 3) Train
    # align
    Xtr, ytr, df_detail_train, feature_order = align_xy(X_train, y_train, stage="train")
    Xva, yva, df_detail_valid, feature_order = align_xy(X_valid, y_valid, stage="valid")
    Xte, yte, df_detail_test, feature_order = align_xy(X_test, y_test, stage="test")
    
    
        
    # 개별 모델 정의
    xgb = XGBClassifier(
        use_label_encoder=False,
        eval_metric='logloss',
        random_state=42
    )

    lgbm = LGBMClassifier(
        n_estimators=200,
        max_depth=7,
        learning_rate=0.1,
        random_state=42
    )

    lr = LogisticRegression(
        C=1.0,
        solver='lbfgs',
        max_iter=1000
    )

    # 스태킹 모델 정의
    stacking_clf = StackingClassifier(
        estimators=[('xgb', xgb), ('lgbm', lgbm), ('lr', lr)],
        final_estimator=LogisticRegression(),   # meta learner
        passthrough=True,                       # 원본 피처도 meta에 함께 사용
        n_jobs=-1
    )

    # 학습
    stacking_clf.fit(Xtr, ytr)
    
    # 학습 직후: 훈련 피처 타입 스냅샷
    train_dtypes = Xtr.dtypes.to_dict()


    # 보정된 모델 생성
    calib_sigmoid = CalibratedClassifierCV(estimator=stacking_clf, method='sigmoid', cv='prefit')
    calib_isotonic = CalibratedClassifierCV(estimator=stacking_clf, method='isotonic', cv='prefit')
    
    
    # ----------------------------- 4) valid, test
    # valid
    # 위에서 stacking_clf.fit(Xtr, ytr) 완료
    calib_sigmoid.fit(Xva, yva)
    calib_isotonic.fit(Xva, yva)
    
    # 확률/지표 계산 ---
    proba_sigmoid_valid  = calib_sigmoid.predict_proba(Xva)[:,1]
    proba_isotonic_valid = calib_isotonic.predict_proba(Xva)[:,1]
    
    valid_results = {}
    for name, proba in [("Sigmoid", proba_sigmoid_valid), ("Isotonic", proba_isotonic_valid)]:
        thr, best_f1 = find_best_threshold(yva, proba)
        y_pred = (proba >= thr).astype(int)
        valid_results[name] = {
            "best_threshold": thr,
            "best_f1": best_f1,
            "accuracy": accuracy_score(yva, y_pred),
            "precision": precision_score(yva, y_pred, zero_division=0),
            "recall": recall_score(yva, y_pred, zero_division=0),
            "f1": f1_score(yva, y_pred, zero_division=0),
            "brier": brier_score_loss(yva, proba),
            "auc": roc_auc_score(yva, proba),
            "confusion_matrix": confusion_matrix(yva, y_pred).tolist(),
            "classification_report": classification_report(yva, y_pred, zero_division=0)
        }
    
    # --- valid 행단위 예측 DF (4컬럼) 생성 ---
    thr_sig = valid_results["Sigmoid"]["best_threshold"]
    thr_iso = valid_results["Isotonic"]["best_threshold"]

    y_pred_sig = (proba_sigmoid_valid >= thr_sig).astype(int)
    y_pred_iso = (proba_isotonic_valid >= thr_iso).astype(int)

    df_valid_pred_sigmoid = pd.DataFrame({
        "date_str":    X_valid["date_str"].values,
        "match_id":    X_valid["match_id"].values,
        "pred_valid":  y_pred_sig,
        "label_valid": yva
    })

    df_valid_pred_isotonic = pd.DataFrame({
        "date_str":    X_valid["date_str"].values,
        "match_id":    X_valid["match_id"].values,
        "pred_valid":  y_pred_iso,
        "label_valid": yva
    })
    
    # test
    proba_sigmoid_test  = calib_sigmoid.predict_proba(Xte)[:, 1]
    proba_isotonic_test = calib_isotonic.predict_proba(Xte)[:, 1]

    # valid에서 구한 임계값 재사용 (데이터 누수 방지)
    thr_sig = valid_results["Sigmoid"]["best_threshold"]
    thr_iso = valid_results["Isotonic"]["best_threshold"]

    y_pred_sig_test = (proba_sigmoid_test >= thr_sig).astype(int)
    y_pred_iso_test = (proba_isotonic_test >= thr_iso).astype(int)

    test_results = {}
    for name, proba, y_pred in [
        ("Sigmoid",  proba_sigmoid_test,  y_pred_sig_test),
        ("Isotonic", proba_isotonic_test, y_pred_iso_test),
    ]:
        test_results[name] = {
            "accuracy":  accuracy_score(yte, y_pred),
            "precision": precision_score(yte, y_pred, zero_division=0),
            "recall":    recall_score(yte, y_pred, zero_division=0),
            "f1":        f1_score(yte, y_pred, zero_division=0),
            "brier":     brier_score_loss(yte, proba),
            "auc":       roc_auc_score(yte, proba),
            "confusion_matrix": confusion_matrix(yte, y_pred).tolist(),
            "classification_report": classification_report(yte, y_pred, zero_division=0),
            "threshold_used": thr_sig if name=="Sigmoid" else thr_iso,
        }

    # 행단위 비교 DF (test)
    df_test_pred_sigmoid = pd.DataFrame({
        "date_str":   X_test["date_str"].values,
        "match_id":   X_test["match_id"].values,
        "pred_test":  y_pred_sig_test,
        "label_test": yte,
    })
    df_test_pred_isotonic = pd.DataFrame({
        "date_str":   X_test["date_str"].values,
        "match_id":   X_test["match_id"].values,
        "pred_test":  y_pred_iso_test,
        "label_test": yte,
    })


    # ----------------------------- 5) new 합성
    """
    임시로 new에서 "game_pk", "date_str", "match_id" 떼어냄
    합성시에 들어가면 안 되기 때문
    
    summarize_prediction_feature()가 명시한 컬럼들만 집계해서 Series를 만들어요. 여기엔 game_pk / date_str / match_id가 애초에 포함돼 있지 않죠.
    그 다음 filter_for_prediction()으로 pitch/swing 규칙으로 또 거르고,
    마지막에 new.reindex(columns=feature_order)에서 학습 시점 피처 순서(메타 제외)로 재정렬하면서 메타가 있어도 자동으로 버려집니다.
    그래서 new_reindex에는 모델 피처만 남는 게 정상 동작이에요.
    """
        
    # 1. summarize

    
    X_new_away_summary = summarize_prediction_feature(X_new_away)
    X_new_home_summary = summarize_prediction_feature(X_new_home)
    
    # summarize()로 압축된 Series이기 때문에 1차원 형태라서, 모델 입력 전에 .to_frame().T로 2차원으로 변환
    X_new_away_summary_T = X_new_away_summary.to_frame().T
    X_new_home_summary_T = X_new_home_summary.to_frame().T
    
    
    # 2. is_pitch
    # 전체 feature 리스트 (fv_a.columns 로부터)
    all_features = X_new_home_summary_T.columns.tolist()

    def filter_for_prediction(fv_row: pd.DataFrame, mode: str, pitch_features, swing_features):
        assert mode in ['home', 'away'], "mode must be 'home' or 'away'"
        
        # 전체 feature 리스트
        all_features = fv_row.columns.tolist()

        # pitch/swing 전체 top/bot 컬럼명
        pitch_features_tb = [f"{feat}_{suffix}" for feat in pitch_features for suffix in ['top', 'bot']]
        swing_features_tb = [f"{feat}_{suffix}" for feat in swing_features for suffix in ['top', 'bot']]

        # 각 feature가 pitch인지 여부
        is_pitch = [feat in pitch_features_tb for feat in all_features]

        # 필터 조건 구성
        keep_mask = []
        for col, pitch_flag in zip(all_features, is_pitch):
            if mode == 'home':
                if col.endswith('_top') and pitch_flag:
                    keep_mask.append(True)  # pitch_top → 남긴다
                    
                elif col.endswith('_bot') and not pitch_flag:
                    keep_mask.append(True)  # swing_bot → 남긴다
                    
                else:
                    keep_mask.append(False) # 나머지는 제거
                    
            elif mode == 'away':
                if col.endswith('_top') and not pitch_flag: 
                    keep_mask.append(True) # swing_top → 남긴다
                    
                elif col.endswith('_bot') and pitch_flag: 
                    keep_mask.append(True) # pitch_bot → 남긴다
                    
                else:
                    keep_mask.append(False) # 나머지는 제거

        # 필터링 적용
        filtered_row = fv_row.loc[:, keep_mask]

        return filtered_row

    X_new_away_filtered = filter_for_prediction(X_new_away_summary_T, mode='away', pitch_features=pitch_features, swing_features=swing_features)
    X_new_home_filtered = filter_for_prediction(X_new_home_summary_T, mode='home', pitch_features=pitch_features, swing_features=swing_features)
    
    # 3. concat
    # 컬럼 방향으로 결합 → shape: (1, 102)
    new = pd.concat([X_new_home_filtered, X_new_away_filtered], axis=1)

    # 학습 당시 feature 순서로 재정렬
    new_reindex = new.reindex(columns=feature_order)
    # 새 샘플(new)의 컬럼/타입 정렬
    """
    (a) 없는 컬럼은 0으로 채우기
    (b) dtype을 훈련셋과 일치시키기
    (c) NaN을 0으로 채우기
    를 해두지 않으면 예측 시 에러/성능저하가 생깁니다.
    """
    """
    # 학습 당시 feature 순서로 재정렬 + 없는 컬럼 0으로 채움
    new_reindex = new.reindex(columns=feature_order, fill_value=0)

    # dtype 일치 (숫자형은 숫자로, 불가시 0으로)
    for c, dt in train_dtypes.items():
        if c not in new_reindex.columns:
            new_reindex[c] = 0
        try:
            new_reindex[c] = new_reindex[c].astype(dt)
        except Exception:
            # 숫자형이면 강제 numeric 변환 후 결측 0 채움
            if np.issubdtype(dt, np.number):
                new_reindex[c] = pd.to_numeric(new_reindex[c], errors="coerce").fillna(0).astype(dt)
            else:
                # 비숫자형은 일단 문자열로 두거나, 필요 시 인코더 재사용
                new_reindex[c] = new_reindex[c].astype(str)

    # 남은 NaN 안전하게 0 채움 (모델이 NaN 못 받는 경우 대비)
    new_reindex = new_reindex.fillna(0)
    """
    
    
    
    # ----------------------------- 6) Prediction
    # 확률(양성=1 클래스) 추출
    proba_sigmoid  = calib_sigmoid.predict_proba(new_reindex)[0]
    proba_isotonic = calib_isotonic.predict_proba(new_reindex)[0]
    # 이건 fv가 하나의 샘플(1 row)이므로, predict_proba(fv) 결과는 (1, 2) shape의 배열입니다.
    # [0]을 붙이면 그 중 첫 번째 (그리고 유일한) row인 확률 벡터 ex) [0.36, 0.64]를 꺼냅니다.
    
    pos_idx_sig = int(np.where(calib_sigmoid.classes_ == 1)[0][0])
    pos_idx_iso = int(np.where(calib_isotonic.classes_ == 1)[0][0])
    
    p_sig = float(proba_sigmoid[pos_idx_sig])
    p_iso = float(proba_isotonic[pos_idx_iso])

    # 라벨 조회(없으면 NaN; 마지막 날짜 250809는 자연스럽게 비게 됨)
    label_val = label_map.get((pred_date, match_id), np.nan)

    # 누적
    pred_rows.append({
        "date_str":       pred_date,
        "match_id":       match_id,
        "proba_sigmoid":  round(p_sig, 6),
        "proba_isotonic": round(p_iso, 6),
        "label":          label_val,
    })

    
    
    # ----------------------------- Excel
    excel_path = f"{WEB_DATA_PATH}{pred_date}_{match_id}.xlsx"
    with pd.ExcelWriter(excel_path, engine="openpyxl") as writer:
        # (a) 기본 변수 sheet
        meta_df = pd.DataFrame({
            "pred_date": [pred_date],
            "match_id": [match_id],
            "window": [window],
            "away_team": [away_team],
            "home_team": [home_team],
            "train_available_date": [train_available_date],
            
            "nX_total": [nX_total],
            "nX_train": [nX_tr],
            "nX_valid": [nX_va],
            "nX_test": [nX_te],
            
            "ny_total": [ny_total],
            "ny_train": [ny_tr],
            "ny_valid": [ny_va],
            "ny_test": [ny_te],
        })
        
        meta_df.to_excel(writer, sheet_name="meta", index=False)

        # (b) away/home_games raw
        pd.DataFrame(away_games).to_excel(writer, sheet_name="away_games", index=False)
        pd.DataFrame(home_games).to_excel(writer, sheet_name="home_games", index=False)

        # (c) new
        summarize_df(X_new_away).to_excel(writer, sheet_name="X_new_away", index=False)
        summarize_df(X_new_home).to_excel(writer, sheet_name="X_new_home", index=False)

        # (d) split 데이터
        summarize_df(X_train).to_excel(writer, sheet_name="X_train", index=False)
        summarize_df(X_valid).to_excel(writer, sheet_name="X_valid", index=False)
        summarize_df(X_test).to_excel(writer, sheet_name="X_test", index=False)

        # (e) cutoff 이전 전체
        summarize_df(X_past_all).to_excel(writer, sheet_name="X_past_all", index=False)
        
        # (f) 
        df_detail_train.to_excel(writer, sheet_name="X, y train data compare", index=False)
        df_detail_valid.to_excel(writer, sheet_name="X, y valid data compare", index=False)
        df_detail_test.to_excel(writer, sheet_name="X, y test data compare", index=False)
        
        # (g) valid pred, label compare
        df_valid_pred_sigmoid.to_excel(writer, sheet_name="valid_pred_sigmoid", index=False)
        df_valid_pred_isotonic.to_excel(writer, sheet_name="valid_pred_isotonic", index=False)
        
        # (h) test pred, label compare
        df_test_pred_sigmoid.to_excel(writer, sheet_name="test_pred_sigmoid", index=False)
        df_test_pred_isotonic.to_excel(writer, sheet_name="test_pred_isotonic", index=False)

        # (i) new build wide (왼쪽 A열: 이름, 오른쪽 가로로 피처명 / 다음 줄에 값)
        sheet_name = "new_build_wide"

        def _write_wide(ws, start_row, label, obj, write_values=True):
            """
            ws: openpyxl Worksheet
            start_row: 시작 행(1-based)
            label: A열에 쓸 블록 이름
            obj: Series / 1-row DataFrame / list(=all_features) / scalar
            write_values: True면 피처명 아래 줄에 값도 씀
            """
            ws.cell(row=start_row, column=1, value=label)

            # 피처명/값 추출
            if isinstance(obj, pd.Series):
                cols = obj.index.tolist()
                vals = obj.values.tolist()
            elif isinstance(obj, pd.DataFrame):
                df = obj
                cols = df.columns.tolist()
                vals = df.iloc[0].tolist() if len(df) > 0 else []
            elif isinstance(obj, (list, tuple, np.ndarray)):
                cols = list(obj)          # all_features 같은 경우
                vals = None               # 값 행은 쓰지 않음
                write_values = False
            else:
                cols = ["value"]
                vals = [obj]

            # 헤더(피처명) 가로로: B열부터
            for j, c in enumerate(cols, start=2):
                ws.cell(row=start_row, column=j, value=c)

            # 값 행(옵션): 다음 줄에 B열부터
            next_row = start_row + 1
            if write_values and vals is not None:
                ws.cell(row=next_row, column=1, value="(values)")
                for j, v in enumerate(vals, start=2):
                    ws.cell(row=next_row, column=j, value=v)
                next_row += 1

            # 보기 좋게 한 줄 띄우기
            return next_row + 1

        # 시트 생성 및 쓰기
        ws = writer.book.create_sheet(title=sheet_name)
        writer.sheets[sheet_name] = ws

        row = 1
        row = _write_wide(ws, row, "X_new_away_summary",   X_new_away_summary,   write_values=True)
        row = _write_wide(ws, row, "X_new_home_summary",   X_new_home_summary,   write_values=True)
        row = _write_wide(ws, row, "X_new_away_summary_T", X_new_away_summary_T, write_values=True)
        row = _write_wide(ws, row, "X_new_home_summary_T", X_new_home_summary_T, write_values=True)
        row = _write_wide(ws, row, "all_features",         all_features,         write_values=False)  # ← 값 없음
        row = _write_wide(ws, row, "X_new_away_filtered",  X_new_away_filtered,  write_values=True)
        row = _write_wide(ws, row, "X_new_home_filtered",  X_new_home_filtered,  write_values=True)
        row = _write_wide(ws, row, "new",                  new,                  write_values=True)
        row = _write_wide(ws, row, "new_reindex",          new_reindex,          write_values=True)
        row = _write_wide(ws, row, "feature_order",        feature_order,        write_values=False)  # ← 값 없음

        


    # ----------------------------- Text
    # valid
    base = f"{WEB_DATA_PATH}{pred_date}_{match_id}"
    
    txt_path = base + "_valid_report.txt"
    _ensure_dir(txt_path)
    with open(txt_path, "w", encoding="utf-8") as fw:
        fw.write(f"[VALID REPORT] pred_date={pred_date}, match_id={match_id}\n")
        fw.write(f"n_valid={len(yva)}\n\n")
        for name, res in valid_results.items():
            fw.write(f"== {name} ==\n")
            fw.write(f"Best Threshold: {res['best_threshold']:.3f} (F1={res['best_f1']:.4f})\n")
            fw.write(f"Accuracy: {res['accuracy']:.4f}\n")
            fw.write(f"Precision: {res['precision']:.4f}\n")
            fw.write(f"Recall: {res['recall']:.4f}\n")
            fw.write(f"F1: {res['f1']:.4f}\n")
            fw.write(f"Brier: {res['brier']:.5f}\n")
            fw.write(f"AUC: {res['auc']:.4f}\n")
            fw.write(f"Confusion Matrix: {json.dumps(res['confusion_matrix'])}\n")
            fw.write("\nClassification Report:\n")
            fw.write(res['classification_report'])
            fw.write("\n" + "-"*60 + "\n")
    
    # test
    txt_path_test = base + "_test_report.txt"
    _ensure_dir(txt_path_test)
    with open(txt_path_test, "w", encoding="utf-8") as fw:
        fw.write(f"[TEST REPORT] pred_date={pred_date}, match_id={match_id}\n")
        fw.write(f"n_test={len(yte)}\n\n")
        for name, res in test_results.items():
            fw.write(f"== {name} == (thr from valid = {res['threshold_used']:.3f})\n")
            fw.write(f"Accuracy: {res['accuracy']:.4f}\n")
            fw.write(f"Precision: {res['precision']:.4f}\n")
            fw.write(f"Recall: {res['recall']:.4f}\n")
            fw.write(f"F1: {res['f1']:.4f}\n")
            fw.write(f"Brier: {res['brier']:.5f}\n")
            fw.write(f"AUC: {res['auc']:.4f}\n")
            fw.write(f"Confusion Matrix: {json.dumps(res['confusion_matrix'])}\n")
            fw.write("\nClassification Report:\n")
            fw.write(res['classification_report'])
            fw.write("\n" + "-"*60 + "\n")        
            
    # ----------------------------- Image
    # valid
    # Confusion Matrix PNG (보정별로 2개)
    for name, proba in [("Sigmoid", proba_sigmoid_valid), ("Isotonic", proba_isotonic_valid)]:
        thr = valid_results[name]["best_threshold"]
        y_pred = (proba >= thr).astype(int)
        out_png = base + f"_valid_confmat_{name}.png"
        save_confmat(yva, y_pred, f"Valid Confusion Matrix - {name}", out_png)

    # Calibration curve PNG (두 보정 비교 1장)
    save_calibration_curve(yva,
                        {"Sigmoid": proba_sigmoid_valid, "Isotonic": proba_isotonic_valid},
                        base + "_valid_calibration.png")

    # ROC curve PNG (두 보정 비교 1장)
    save_roc(yva,
            {"Sigmoid": proba_sigmoid_valid, "Isotonic": proba_isotonic_valid},
            base + "_valid_roc.png")
    
    # test
    for name, proba, y_pred in [
        ("Sigmoid",  proba_sigmoid_test,  y_pred_sig_test),
        ("Isotonic", proba_isotonic_test, y_pred_iso_test),
    ]:
        out_png = base + f"_test_confmat_{name}.png"
        save_confmat(yte, y_pred, f"Test Confusion Matrix - {name}", out_png)

    save_calibration_curve(yte,
        {"Sigmoid": proba_sigmoid_test, "Isotonic": proba_isotonic_test},
        base + "_test_calibration.png")
    save_roc(yte,
        {"Sigmoid": proba_sigmoid_test, "Isotonic": proba_isotonic_test},
        base + "_test_roc.png")
    
    
    
# new 데이터들을 모델에 넣고 나온 confusion matrix 등의 누적 지표 저장
if pred_rows:
    pred_df = pd.DataFrame(pred_rows).sort_values(["date_str","match_id"])
    date_min = pred_df["date_str"].min()
    date_max = pred_df["date_str"].max()

    out_path = f"{WEB_DATA_PATH}_{date_min}-{date_max}_pred.xlsx"  # 예: .../250522-250809_pred.xlsx
    pred_df.to_excel(out_path, sheet_name="predictions", index=False)
    print(f"✅ Saved prediction summary: {out_path}  ({len(pred_df)} rows)")
else:
    print("⚠️ No predictions to save.")

repeat_limit (정한 매치 수) :  None
num_matches: 1163 | repeat_count: 1163
✅ Saved prediction summary: ../web_data/_250522-250821_pred.xlsx  (1169 rows)

# 3. Train

## valid

## test

# 4. Eval

In [ ]:
# corr, VIF, PCA, SHAP

# 5. Prediction

## Single Match

## Multiple Match